/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.project;

import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JFrame;

/**
 *
 * @author momo
 */
public class add extends javax.swing.JFrame {

    /**
     * Creates new form add_employee
     */
    public static JFrame temp_add;
    public add(JFrame parent) {
        initComponents();
                this.setResizable(false); 
        this.setLocationRelativeTo(null);
        temp_add = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        type_box = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pass_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        id_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fname_txt = new javax.swing.JTextField();
        mname_txt = new javax.swing.JTextField();
        lname_txt = new javax.swing.JTextField();
        sex_box = new javax.swing.JComboBox<>();
        year_txt = new javax.swing.JTextField();
        month_txt = new javax.swing.JTextField();
        day_txt = new javax.swing.JTextField();
        phone_txt = new javax.swing.JTextField();
        salary_txt = new javax.swing.JTextField();
        shift_box = new javax.swing.JComboBox<>();
        address_txt = new javax.swing.JTextField();
        dep = new javax.swing.JLabel();
        Specialty = new javax.swing.JLabel();
        Specialty_txt = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        dep_box = new javax.swing.JComboBox<>();
        city_box = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dep_name_txt = new javax.swing.JTextField();
        beds_txt = new javax.swing.JTextField();
        floor = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        pid = new javax.swing.JTextField();
        pfname = new javax.swing.JTextField();
        pmname = new javax.swing.JTextField();
        plname = new javax.swing.JTextField();
        psex = new javax.swing.JComboBox<>();
        pblood = new javax.swing.JComboBox<>();
        pyear = new javax.swing.JTextField();
        pmonth = new javax.swing.JTextField();
        pday = new javax.swing.JTextField();
        pnum = new javax.swing.JTextField();
        pcitybox = new javax.swing.JComboBox<>();
        pdep = new javax.swing.JComboBox<>();
        pcity = new javax.swing.JTextField();
        ConfirmAdditionPatientButton = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jTabbedPane3.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane3.setForeground(new java.awt.Color(0, 0, 0));
        jTabbedPane3.setName("Add Employee"); // NOI18N
        jTabbedPane3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane3FocusGained(evt);
            }
        });
        jTabbedPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane3MouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(217, 244, 255));
        jPanel2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel2FocusGained(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(null);

        type_box.setBackground(new java.awt.Color(204, 204, 204));
        type_box.setForeground(new java.awt.Color(0, 0, 0));
        type_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Doctor", "Nurse", "Lab Technician" }));
        type_box.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                type_boxComponentHidden(evt);
            }
        });
        type_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type_boxActionPerformed(evt);
            }
        });
        jPanel2.add(type_box);
        type_box.setBounds(130, 40, 119, 22);

        jLabel21.setBackground(new java.awt.Color(255, 204, 102));
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Password");
        jLabel21.setOpaque(true);
        jPanel2.add(jLabel21);
        jLabel21.setBounds(440, 100, 88, 21);

        jLabel1.setBackground(new java.awt.Color(255, 204, 102));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Employee Type");
        jLabel1.setOpaque(true);
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 40, 88, 21);

        jLabel2.setBackground(new java.awt.Color(255, 204, 102));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ID");
        jLabel2.setOpaque(true);
        jPanel2.add(jLabel2);
        jLabel2.setBounds(440, 50, 88, 21);

        jLabel3.setBackground(new java.awt.Color(255, 204, 102));
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Name");
        jLabel3.setOpaque(true);
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 90, 88, 21);

        pass_txt.setBackground(new java.awt.Color(204, 204, 204));
        pass_txt.setForeground(new java.awt.Color(0, 0, 0));
        pass_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pass_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_txtActionPerformed(evt);
            }
        });
        jPanel2.add(pass_txt);
        pass_txt.setBounds(560, 100, 156, 22);

        jLabel4.setBackground(new java.awt.Color(255, 204, 102));
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Sex");
        jLabel4.setOpaque(true);
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 250, 88, 21);

        jLabel5.setBackground(new java.awt.Color(255, 204, 102));
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Birth date");
        jLabel5.setOpaque(true);
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 200, 88, 21);

        jLabel6.setBackground(new java.awt.Color(255, 204, 102));
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Phone Number");
        jLabel6.setOpaque(true);
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 350, 88, 21);

        jLabel7.setBackground(new java.awt.Color(255, 204, 102));
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Salary");
        jLabel7.setOpaque(true);
        jPanel2.add(jLabel7);
        jLabel7.setBounds(440, 150, 88, 21);

        jLabel8.setBackground(new java.awt.Color(255, 204, 102));
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Shift");
        jLabel8.setOpaque(true);
        jPanel2.add(jLabel8);
        jLabel8.setBounds(440, 200, 88, 21);

        id_txt.setBackground(new java.awt.Color(204, 204, 204));
        id_txt.setForeground(new java.awt.Color(0, 0, 0));
        id_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        id_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                id_txtFocusGained(evt);
            }
        });
        id_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_txtActionPerformed(evt);
            }
        });
        jPanel2.add(id_txt);
        id_txt.setBounds(560, 50, 156, 22);

        jLabel9.setBackground(new java.awt.Color(255, 204, 102));
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Address");
        jLabel9.setOpaque(true);
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 300, 88, 21);

        fname_txt.setBackground(new java.awt.Color(204, 204, 204));
        fname_txt.setForeground(new java.awt.Color(102, 102, 102));
        fname_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fname_txt.setText("First Name");
        fname_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fname_txtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fname_txtFocusLost(evt);
            }
        });
        fname_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fname_txtActionPerformed(evt);
            }
        });
        jPanel2.add(fname_txt);
        fname_txt.setBounds(130, 90, 150, 22);

        mname_txt.setBackground(new java.awt.Color(204, 204, 204));
        mname_txt.setForeground(new java.awt.Color(102, 102, 102));
        mname_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mname_txt.setText("Middle Name");
        mname_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mname_txtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mname_txtFocusLost(evt);
            }
        });
        jPanel2.add(mname_txt);
        mname_txt.setBounds(130, 120, 150, 22);

        lname_txt.setBackground(new java.awt.Color(204, 204, 204));
        lname_txt.setForeground(new java.awt.Color(102, 102, 102));
        lname_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lname_txt.setText("Last Name");
        lname_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lname_txtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lname_txtFocusLost(evt);
            }
        });
        jPanel2.add(lname_txt);
        lname_txt.setBounds(130, 150, 150, 22);

        sex_box.setBackground(new java.awt.Color(204, 204, 204));
        sex_box.setForeground(new java.awt.Color(0, 0, 0));
        sex_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        jPanel2.add(sex_box);
        sex_box.setBounds(130, 250, 55, 22);

        year_txt.setBackground(new java.awt.Color(204, 204, 204));
        year_txt.setForeground(new java.awt.Color(102, 102, 102));
        year_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        year_txt.setText("YYYY");
        year_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                year_txtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                year_txtFocusLost(evt);
            }
        });
        jPanel2.add(year_txt);
        year_txt.setBounds(130, 200, 71, 22);

        month_txt.setBackground(new java.awt.Color(204, 204, 204));
        month_txt.setForeground(new java.awt.Color(102, 102, 102));
        month_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        month_txt.setText("MM");
        month_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                month_txtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                month_txtFocusLost(evt);
            }
        });
        jPanel2.add(month_txt);
        month_txt.setBounds(210, 200, 71, 22);

        day_txt.setBackground(new java.awt.Color(204, 204, 204));
        day_txt.setForeground(new java.awt.Color(102, 102, 102));
        day_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        day_txt.setText("DD");
        day_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                day_txtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                day_txtFocusLost(evt);
            }
        });
        jPanel2.add(day_txt);
        day_txt.setBounds(290, 200, 71, 22);

        phone_txt.setBackground(new java.awt.Color(204, 204, 204));
        phone_txt.setForeground(new java.awt.Color(0, 0, 0));
        phone_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(phone_txt);
        phone_txt.setBounds(130, 350, 148, 22);

        salary_txt.setBackground(new java.awt.Color(204, 204, 204));
        salary_txt.setForeground(new java.awt.Color(0, 0, 0));
        salary_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(salary_txt);
        salary_txt.setBounds(560, 150, 70, 22);

        shift_box.setBackground(new java.awt.Color(204, 204, 204));
        shift_box.setForeground(new java.awt.Color(0, 0, 0));
        shift_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C" }));
        jPanel2.add(shift_box);
        shift_box.setBounds(560, 200, 45, 22);

        address_txt.setEditable(false);
        address_txt.setBackground(new java.awt.Color(204, 204, 204));
        address_txt.setForeground(new java.awt.Color(102, 102, 102));
        address_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        address_txt.setText("City");
        address_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                address_txtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                address_txtFocusLost(evt);
            }
        });
        address_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address_txtActionPerformed(evt);
            }
        });
        jPanel2.add(address_txt);
        address_txt.setBounds(240, 300, 136, 22);

        dep.setBackground(new java.awt.Color(255, 204, 102));
        dep.setForeground(new java.awt.Color(0, 0, 0));
        dep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dep.setText("Department");
        dep.setOpaque(true);
        jPanel2.add(dep);
        dep.setBounds(440, 250, 88, 21);

        Specialty.setBackground(new java.awt.Color(255, 204, 102));
        Specialty.setForeground(new java.awt.Color(0, 0, 0));
        Specialty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Specialty.setText("Specialty");
        Specialty.setOpaque(true);
        jPanel2.add(Specialty);
        Specialty.setBounds(10, 400, 88, 21);

        Specialty_txt.setBackground(new java.awt.Color(204, 204, 204));
        Specialty_txt.setForeground(new java.awt.Color(0, 0, 0));
        Specialty_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Specialty_txt.setToolTipText("");
        jPanel2.add(Specialty_txt);
        Specialty_txt.setBounds(130, 400, 136, 22);

        jButton2.setBackground(new java.awt.Color(153, 204, 255));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Confirm");
        jButton2.setAlignmentX(1.0F);
        jButton2.setAlignmentY(1.0F);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(370, 450, 170, 40);

        jButton1.setBackground(new java.awt.Color(255, 204, 153));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Go Back");
        jButton1.setAlignmentX(1.0F);
        jButton1.setAlignmentY(1.0F);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(580, 450, 170, 40);

        dep_box.setBackground(new java.awt.Color(204, 204, 204));
        dep_box.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(dep_box);
        dep_box.setBounds(560, 250, 120, 22);

        city_box.setBackground(new java.awt.Color(204, 204, 204));
        city_box.setForeground(new java.awt.Color(0, 0, 0));
        city_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tulkarm", "Jenin", "Gaza", "Nablus", "Jerusalem", "Qalqilya", "Jericho", "Hebron", "Bethlehem", "Ramallah", "Other" }));
        city_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                city_boxActionPerformed(evt);
            }
        });
        jPanel2.add(city_box);
        city_box.setBounds(130, 300, 91, 22);

        jTabbedPane3.addTab("Add Employee", jPanel2);

        jPanel3.setBackground(new java.awt.Color(217, 244, 255));
        jPanel3.setLayout(null);

        jLabel10.setBackground(new java.awt.Color(255, 204, 102));
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Name");
        jLabel10.setOpaque(true);
        jPanel3.add(jLabel10);
        jLabel10.setBounds(230, 100, 120, 30);

        jLabel11.setBackground(new java.awt.Color(255, 204, 102));
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Floor");
        jLabel11.setOpaque(true);
        jPanel3.add(jLabel11);
        jLabel11.setBounds(230, 180, 120, 30);

        jLabel12.setBackground(new java.awt.Color(255, 204, 102));
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Number Of Beds");
        jLabel12.setOpaque(true);
        jPanel3.add(jLabel12);
        jLabel12.setBounds(230, 260, 120, 30);

        dep_name_txt.setBackground(new java.awt.Color(204, 204, 204));
        dep_name_txt.setForeground(new java.awt.Color(102, 102, 102));
        dep_name_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dep_name_txt.setText("Name");
        dep_name_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dep_name_txtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dep_name_txtFocusLost(evt);
            }
        });
        jPanel3.add(dep_name_txt);
        dep_name_txt.setBounds(390, 100, 180, 30);

        beds_txt.setEditable(false);
        beds_txt.setBackground(new java.awt.Color(204, 204, 204));
        beds_txt.setForeground(new java.awt.Color(0, 0, 0));
        beds_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        beds_txt.setText("6");
        beds_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beds_txtActionPerformed(evt);
            }
        });
        jPanel3.add(beds_txt);
        beds_txt.setBounds(390, 260, 80, 30);

        floor.setBackground(new java.awt.Color(204, 204, 204));
        floor.setForeground(new java.awt.Color(0, 0, 0));
        floor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "G", "1st", "2nd", "3rd" }));
        jPanel3.add(floor);
        floor.setBounds(390, 180, 50, 30);

        jButton3.setBackground(new java.awt.Color(153, 204, 255));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Confirm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(180, 410, 170, 40);

        jButton4.setBackground(new java.awt.Color(255, 204, 153));
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Go Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(430, 410, 170, 40);

        jTabbedPane3.addTab("Add Depratment", jPanel3);

        jPanel4.setBackground(new java.awt.Color(217, 244, 255));
        jPanel4.setLayout(null);

        jLabel17.setBackground(new java.awt.Color(255, 204, 102));
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Birth Date");
        jLabel17.setOpaque(true);
        jPanel4.add(jLabel17);
        jLabel17.setBounds(10, 160, 88, 21);

        jLabel13.setBackground(new java.awt.Color(255, 204, 102));
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("ID");
        jLabel13.setOpaque(true);
        jPanel4.add(jLabel13);
        jLabel13.setBounds(440, 50, 88, 21);

        jLabel14.setBackground(new java.awt.Color(255, 204, 102));
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Name");
        jLabel14.setOpaque(true);
        jPanel4.add(jLabel14);
        jLabel14.setBounds(10, 50, 88, 21);

        jLabel15.setBackground(new java.awt.Color(255, 204, 102));
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Sex");
        jLabel15.setOpaque(true);
        jPanel4.add(jLabel15);
        jLabel15.setBounds(10, 210, 88, 21);

        jLabel16.setBackground(new java.awt.Color(255, 204, 102));
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Blood Type");
        jLabel16.setOpaque(true);
        jPanel4.add(jLabel16);
        jLabel16.setBounds(440, 100, 88, 21);

        jLabel18.setBackground(new java.awt.Color(255, 204, 102));
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Phone Number");
        jLabel18.setOpaque(true);
        jPanel4.add(jLabel18);
        jLabel18.setBounds(10, 310, 88, 21);

        jLabel19.setBackground(new java.awt.Color(255, 204, 102));
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Address");
        jLabel19.setOpaque(true);
        jPanel4.add(jLabel19);
        jLabel19.setBounds(10, 260, 88, 21);

        jLabel20.setBackground(new java.awt.Color(255, 204, 102));
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Department");
        jLabel20.setOpaque(true);
        jPanel4.add(jLabel20);
        jLabel20.setBounds(440, 150, 88, 21);

        pid.setBackground(new java.awt.Color(204, 204, 204));
        pid.setForeground(new java.awt.Color(0, 0, 0));
        pid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(pid);
        pid.setBounds(560, 50, 156, 22);

        pfname.setBackground(new java.awt.Color(204, 204, 204));
        pfname.setForeground(new java.awt.Color(102, 102, 102));
        pfname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pfname.setText("First Name");
        pfname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pfnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pfnameFocusLost(evt);
            }
        });
        jPanel4.add(pfname);
        pfname.setBounds(130, 50, 150, 22);

        pmname.setBackground(new java.awt.Color(204, 204, 204));
        pmname.setForeground(new java.awt.Color(102, 102, 102));
        pmname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pmname.setText("Middle Name");
        pmname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pmnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pmnameFocusLost(evt);
            }
        });
        jPanel4.add(pmname);
        pmname.setBounds(130, 80, 150, 22);

        plname.setBackground(new java.awt.Color(204, 204, 204));
        plname.setForeground(new java.awt.Color(102, 102, 102));
        plname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        plname.setText("Last Name");
        plname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                plnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                plnameFocusLost(evt);
            }
        });
        jPanel4.add(plname);
        plname.setBounds(130, 110, 150, 22);

        psex.setBackground(new java.awt.Color(204, 204, 204));
        psex.setForeground(new java.awt.Color(0, 0, 0));
        psex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        jPanel4.add(psex);
        psex.setBounds(130, 210, 55, 22);

        pblood.setBackground(new java.awt.Color(204, 204, 204));
        pblood.setForeground(new java.awt.Color(0, 0, 0));
        pblood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        jPanel4.add(pblood);
        pblood.setBounds(570, 100, 57, 22);

        pyear.setBackground(new java.awt.Color(204, 204, 204));
        pyear.setForeground(new java.awt.Color(102, 102, 102));
        pyear.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pyear.setText("YYYY");
        pyear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pyearFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pyearFocusLost(evt);
            }
        });
        jPanel4.add(pyear);
        pyear.setBounds(130, 160, 71, 22);

        pmonth.setBackground(new java.awt.Color(204, 204, 204));
        pmonth.setForeground(new java.awt.Color(102, 102, 102));
        pmonth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pmonth.setText("MM");
        pmonth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pmonthFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pmonthFocusLost(evt);
            }
        });
        jPanel4.add(pmonth);
        pmonth.setBounds(210, 160, 71, 22);

        pday.setBackground(new java.awt.Color(204, 204, 204));
        pday.setForeground(new java.awt.Color(102, 102, 102));
        pday.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pday.setText("DD");
        pday.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pdayFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pdayFocusLost(evt);
            }
        });
        jPanel4.add(pday);
        pday.setBounds(290, 160, 71, 22);

        pnum.setBackground(new java.awt.Color(204, 204, 204));
        pnum.setForeground(new java.awt.Color(0, 0, 0));
        pnum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(pnum);
        pnum.setBounds(130, 310, 148, 22);

        pcitybox.setBackground(new java.awt.Color(204, 204, 204));
        pcitybox.setForeground(new java.awt.Color(0, 0, 0));
        pcitybox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tulkarm", "Jenin", "Gaza", "Nablus", "Jerusalem", "Qalqilya", "Jericho", "Hebron", "Bethlehem", "Ramallah", "Other" }));
        pcitybox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcityboxActionPerformed(evt);
            }
        });
        jPanel4.add(pcitybox);
        pcitybox.setBounds(130, 260, 91, 22);

        pdep.setBackground(new java.awt.Color(204, 204, 204));
        pdep.setForeground(new java.awt.Color(0, 0, 0));
        pdep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jPanel4.add(pdep);
        pdep.setBounds(570, 150, 120, 22);

        pcity.setEditable(false);
        pcity.setBackground(new java.awt.Color(204, 204, 204));
        pcity.setForeground(new java.awt.Color(102, 102, 102));
        pcity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pcity.setText("City");
        pcity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pcityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pcityFocusLost(evt);
            }
        });
        jPanel4.add(pcity);
        pcity.setBounds(240, 260, 136, 22);

        ConfirmAdditionPatientButton.setBackground(new java.awt.Color(153, 204, 255));
        ConfirmAdditionPatientButton.setForeground(new java.awt.Color(0, 0, 0));
        ConfirmAdditionPatientButton.setText("Confirm");
        ConfirmAdditionPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmAdditionPatientButtonActionPerformed(evt);
            }
        });
        jPanel4.add(ConfirmAdditionPatientButton);
        ConfirmAdditionPatientButton.setBounds(370, 450, 170, 40);

        jButton6.setBackground(new java.awt.Color(255, 204, 153));
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setText("Go back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);
        jButton6.setBounds(580, 450, 170, 40);

        jTabbedPane3.addTab("Add Patient", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void type_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type_boxActionPerformed
        // TODO add your handling code here:
        if(this.type_box.getSelectedItem().equals("Doctor")){
            this.dep_box.setVisible(true);
            this.dep.setVisible(true);
            this.Specialty_txt.setVisible(true);
            this.Specialty.setVisible(true);
        }
         if(this.type_box.getSelectedItem().equals("Nurse")){
            this.dep_box.setVisible(true);
            this.dep.setVisible(true);
            this.Specialty_txt.setVisible(false);
            this.Specialty.setVisible(false);
        }
         if(this.type_box.getSelectedItem().equals("Lab Technician")){
            this.dep_box.setVisible(false);
            this.dep.setVisible(false);
            this.Specialty_txt.setVisible(false);
            this.Specialty.setVisible(false);
        }
        
        
    }//GEN-LAST:event_type_boxActionPerformed

    private void id_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_txtActionPerformed

    private void fname_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fname_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fname_txtActionPerformed

    private void type_boxComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_type_boxComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_type_boxComponentHidden

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try {
            // TODO add your handling code here:
            DriverManager.registerDriver(new org.postgresql.Driver());
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo,"hmd","0000");
            con.setAutoCommit(false);
            String city=this.city_box.getSelectedItem().toString();
            String qry4="";
            if(this.city_box.getSelectedItem().equals("Other")){
            city=this.address_txt.getText();}
            String qry1="insert into proj_1.employee values ('"+this.id_txt.getText()+"','"
                    +this.fname_txt.getText()+"','"+this.mname_txt.getText()+"','"+this.lname_txt.getText()+"','"
                    +this.sex_box.getSelectedItem()+"','"+this.year_txt.getText()+"-"+this.month_txt.getText()+"-"
                    +this.day_txt.getText()+"','"+this.phone_txt.getText()+"',"+this.salary_txt.getText()+",'"
                    +this.shift_box.getSelectedItem()+"','"+city+"', '"+this.pass_txt.getText()+"')";
            String qry2 = null;
            int count_nurse=0;
            int flag=0;
            String qry3="SELECT e.emp_id FROM proj_1.employee AS e "
                    + "INNER JOIN proj_1.lab_technician AS lt ON e.emp_id = lt.emp_id "
                    + "where shift='"+this.shift_box.getSelectedItem()+"'";
            String tech_id="";
            Statement stmt=con.createStatement();
            if (this.type_box.getSelectedItem().equals("Doctor") || this.type_box.getSelectedItem().equals("Nurse")){
            ResultSet rs= stmt.executeQuery(qry3);
             while(rs.next()){ 
                 tech_id=rs.getString(1);
                 System.out.println(tech_id);
                    }}
             String count_nurse_qry="select count(*) from proj_1.nurse as n,proj_1.employee as e "
                     + "where e.emp_id=n.emp_id and "
                     + "n.dep_name='"+this.dep_box.getSelectedItem()+"' "
                     + "and e.shift='"+this.shift_box.getSelectedItem()+"'";
           
            ResultSet rs=stmt.executeQuery(count_nurse_qry);
            while(rs.next()){
            count_nurse=rs.getInt(1);
            }
            if(this.type_box.getSelectedItem().equals("Nurse") && (count_nurse>=2)){
            JOptionPane.showMessageDialog(null, "Nurses at full capacity.", "Warning.", JOptionPane.INFORMATION_MESSAGE);
            return;
            }
            if (this.type_box.getSelectedItem().equals("Doctor")){
                qry2="insert into proj_1.doctor values('"+this.id_txt.getText()+"','"+this.dep_box.getSelectedItem()+"','"+this.Specialty_txt.getText()+"','"+tech_id+"',null,'false','"+this.pass_txt.getText()+"')";}
            if (this.type_box.getSelectedItem().equals("Nurse")){
                qry2="insert into proj_1.nurse values('"+this.id_txt.getText()+"','"+this.dep_box.getSelectedItem()+"','"+this.pass_txt.getText()+"')";
                qry4="insert into proj_1.nurse_tech(nurse_id,tech_id) values ('"+this.id_txt.getText()+"','"+tech_id+"')";
                flag=1;}
            if (this.type_box.getSelectedItem().equals("Lab Technician")){
                qry2="insert into proj_1.Lab_technician values('"+this.id_txt.getText()+"','Laboratory','"+this.pass_txt.getText()+"')";}
            stmt.executeUpdate(qry1);
            stmt.executeUpdate(qry2);
            if(flag==1){
            stmt.executeUpdate(qry4);}
            con.commit();
            con.close();
            JOptionPane.showMessageDialog(null, "Done");
        } catch (Exception ex) {
            //Logger.getLogger(ayo.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(null,ex.toString());
        } 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           // TODO add your handling code here:
           temp_add.setVisible(true);
           this.dispose();
           
          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fname_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fname_txtFocusGained
        // TODO add your handling code here:
        if (fname_txt.getText().equals("First Name")) {
                    fname_txt.setText("");
                    fname_txt.setForeground(Color.black);
        }
    }//GEN-LAST:event_fname_txtFocusGained

    private void fname_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fname_txtFocusLost
        // TODO add your handling code here:
        if (fname_txt.getText().isEmpty()) {
                    fname_txt.setText("First Name");
                    fname_txt.setForeground(Color.GRAY);
                }
    }//GEN-LAST:event_fname_txtFocusLost

    private void mname_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mname_txtFocusGained
        // TODO add your handling code here:
        if (mname_txt.getText().equals("Middle Name")) {
                    mname_txt.setText("");
        mname_txt.setForeground(Color.black);}
    }//GEN-LAST:event_mname_txtFocusGained

    private void mname_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mname_txtFocusLost
        // TODO add your handling code here:
        if (mname_txt.getText().isEmpty()) {
                    mname_txt.setText("Middle Name");
                    mname_txt.setForeground(Color.GRAY);
                }
    }//GEN-LAST:event_mname_txtFocusLost

    private void lname_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lname_txtFocusGained
        // TODO add your handling code here:
        if (lname_txt.getText().equals("Last Name")) {
                    lname_txt.setText("");
        lname_txt.setForeground(Color.black);}
    }//GEN-LAST:event_lname_txtFocusGained

    private void lname_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lname_txtFocusLost
        // TODO add your handling code here:
        if (lname_txt.getText().isEmpty()) {
                    lname_txt.setText("Last Name");
                    lname_txt.setForeground(Color.GRAY);
                }
    }//GEN-LAST:event_lname_txtFocusLost

    private void year_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_year_txtFocusGained
        // TODO add your handling code here:
         if (year_txt.getText().equals("YYYY")) {
                    year_txt.setText("");
         year_txt.setForeground(Color.black);}
        
    }//GEN-LAST:event_year_txtFocusGained

    private void year_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_year_txtFocusLost
        // TODO add your handling code here:
         if (year_txt.getText().isEmpty()) {
                    year_txt.setText("YYYY");
                    year_txt.setForeground(Color.GRAY);
                }
    }//GEN-LAST:event_year_txtFocusLost

    private void month_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_month_txtFocusGained
        // TODO add your handling code here:
        if (month_txt.getText().equals("MM")) {
                    month_txt.setText("");
            month_txt.setForeground(Color.black);}
    }//GEN-LAST:event_month_txtFocusGained

    private void month_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_month_txtFocusLost
        // TODO add your handling code here:
         if (month_txt.getText().isEmpty()) {
                    month_txt.setText("MM");
                    month_txt.setForeground(Color.GRAY);
                }
    }//GEN-LAST:event_month_txtFocusLost

    private void day_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_day_txtFocusGained
        // TODO add your handling code here:
         if (day_txt.getText().equals("DD")) {
                    day_txt.setText("");
         day_txt.setForeground(Color.black);}
    }//GEN-LAST:event_day_txtFocusGained

    private void day_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_day_txtFocusLost
        // TODO add your handling code here:
        if (day_txt.getText().isEmpty()) {
                    day_txt.setText("DD");
                    day_txt.setForeground(Color.GRAY);
                }
    }//GEN-LAST:event_day_txtFocusLost

    private void jPanel2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel2FocusGained
      // TODO add your handling code here:

    }//GEN-LAST:event_jPanel2FocusGained

    private void jTabbedPane3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane3FocusGained
        // TODO add your handling code here:
                try {
            DriverManager.registerDriver(new org.postgresql.Driver());
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo,"hmd","0000");
            String sql="select dep_name from proj_1.department";
            Statement stmt=con.createStatement();
            ResultSet rs= stmt.executeQuery(sql);
            this.dep_box.removeAllItems();
            this.pdep.removeAllItems();
            while(rs.next()){
                String depname=rs.getString(1);
                this.dep_box.addItem(depname);
                this.pdep.addItem(depname);
            }
            con.close();
    } catch (Exception ex) {
            //Logger.getLogger(ayo.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(null,ex.toString());
        }
        
    }//GEN-LAST:event_jTabbedPane3FocusGained

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jTabbedPane3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane3MouseClicked

    private void beds_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beds_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beds_txtActionPerformed

    private void dep_name_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dep_name_txtFocusGained
        // TODO add your handling code here:
        if (dep_name_txt.getText().equals("Name")) {
                    dep_name_txt.setForeground(Color.black);
                    dep_name_txt.setText("");}
    }//GEN-LAST:event_dep_name_txtFocusGained

    private void dep_name_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dep_name_txtFocusLost
        // TODO add your handling code here:
        if (dep_name_txt.getText().isEmpty()) {
            dep_name_txt.setForeground(Color.GRAY);
                    dep_name_txt.setText("Name");
                }
    }//GEN-LAST:event_dep_name_txtFocusLost

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        temp_add.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            DriverManager.registerDriver(new org.postgresql.Driver());
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo,"hmd","0000");
            con.setAutoCommit(false);
            String qry="insert into proj_1.department values ('"+this.dep_name_txt.getText()+"','"+this.floor.getSelectedItem()+"',"+this.beds_txt.getText()+")";
            Statement stmt=con.createStatement();
            stmt.executeUpdate(qry);
            con.commit();
            con.close();
            JOptionPane.showMessageDialog(null, "Done");
        } catch (Exception ex) {
            //Logger.getLogger(ayo.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(null,ex.toString());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void address_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_address_txtFocusLost
        // TODO add your handling code here:
        if (address_txt.getText().isEmpty()) {
            address_txt.setText("City");
        }
    }//GEN-LAST:event_address_txtFocusLost

    private void address_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_address_txtFocusGained
        // TODO add your handling code here:
        if (address_txt.getText().equals("City")&&(address_txt.isEditable()==true)) {
            address_txt.setText("");}
    }//GEN-LAST:event_address_txtFocusGained

    private void city_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_city_boxActionPerformed
        // TODO add your handling code here:
        if(this.city_box.getSelectedItem().equals("Other")){
            this.address_txt.setEditable(true);
            this.address_txt.setForeground(Color.black);
        }
        else{
            this.address_txt.setEditable(false);
            this.address_txt.setForeground(Color.GRAY);}
    }//GEN-LAST:event_city_boxActionPerformed

    private void address_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address_txtActionPerformed

    private void pfnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfnameFocusGained
        // TODO add your handling code here:
        if (pfname.getText().equals("First Name")) {
                    pfname.setForeground(Color.black);
                    pfname.setText("");}
    }//GEN-LAST:event_pfnameFocusGained

    private void pfnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfnameFocusLost
        // TODO add your handling code here:
        if (pfname.getText().isEmpty()) {
            pfname.setForeground(Color.gray);
            pfname.setText("First Name");}
        
    }//GEN-LAST:event_pfnameFocusLost

    private void pmnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pmnameFocusGained
        // TODO add your handling code here:
        if (pmname.getText().equals("Middle Name")) {
            pmname.setForeground(Color.black);
                    pmname.setText("");}
    }//GEN-LAST:event_pmnameFocusGained

    private void pmnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pmnameFocusLost
        // TODO add your handling code here:
        if (pmname.getText().isEmpty()) {
            pmname.setForeground(Color.gray);
            pmname.setText("Middle Name");}
    }//GEN-LAST:event_pmnameFocusLost

    private void plnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_plnameFocusGained
        // TODO add your handling code here:
        if (plname.getText().equals("Last Name")) {
                    plname.setForeground(Color.black);
                    plname.setText("");}
    }//GEN-LAST:event_plnameFocusGained

    private void plnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_plnameFocusLost
        // TODO add your handling code here:
         if (plname.getText().isEmpty()) {
             plname.setForeground(Color.gray);
            plname.setText("Last Name");}
    }//GEN-LAST:event_plnameFocusLost

    private void pyearFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pyearFocusGained
        // TODO add your handling code here:
        if (pyear.getText().equals("YYYY")) {
                pyear.setForeground(Color.black);
                    pyear.setText("");}
    }//GEN-LAST:event_pyearFocusGained

    private void pyearFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pyearFocusLost
        // TODO add your handling code here:
        if (pyear.getText().isEmpty()) {
            pyear.setForeground(Color.gray);
            pyear.setText("YYYY");}
    }//GEN-LAST:event_pyearFocusLost

    private void pmonthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pmonthFocusGained
        // TODO add your handling code here:
        if (pmonth.getText().equals("MM")) {
            pmonth.setForeground(Color.black);
                    pmonth.setText("");}
    }//GEN-LAST:event_pmonthFocusGained

    private void pmonthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pmonthFocusLost
        // TODO add your handling code here:
        if (pmonth.getText().isEmpty()) {
            pmonth.setForeground(Color.gray);
            pmonth.setText("MM");}
    }//GEN-LAST:event_pmonthFocusLost

    private void pdayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pdayFocusGained
        // TODO add your handling code here:
        if (pday.getText().equals("DD")) {
                    pday.setForeground(Color.black);
                    pday.setText("");}
    }//GEN-LAST:event_pdayFocusGained

    private void pdayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pdayFocusLost
        // TODO add your handling code here:
        if (pday.getText().isEmpty()) {
            pday.setForeground(Color.gray);
            pday.setText("DD");}
    }//GEN-LAST:event_pdayFocusLost

    private void pcityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pcityFocusGained
        // TODO add your handling code here:
        if (pcity.getText().equals("City")&&(pcity.isEditable()==true)) {
            pcity.setText("");}
    }//GEN-LAST:event_pcityFocusGained

    private void pcityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pcityFocusLost
        // TODO add your handling code here:
        if (pcity.getText().isEmpty()) {
            pcity.setText("City");
        }
    }//GEN-LAST:event_pcityFocusLost

    private void pcityboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcityboxActionPerformed
        // TODO add your handling code here:
         if(this.pcitybox.getSelectedItem().equals("Other")){
            this.pcity.setEditable(true);
            this.pcity.setForeground(Color.black);}
         else{
            this.pcity.setEditable(false);
            this.pcity.setForeground(Color.GRAY);
         }
    }//GEN-LAST:event_pcityboxActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        temp_add.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void ConfirmAdditionPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmAdditionPatientButtonActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            DriverManager.registerDriver(new org.postgresql.Driver());
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo,"hmd","0000");
            con.setAutoCommit(false);
            String city=this.pcitybox.getSelectedItem().toString();
            if(this.pcitybox.getSelectedItem().equals("Other")){
            city=this.pcity.getText();}
            String nurse_id="";
            int count=0;
            int count2=0;
            String qry="SELECT emp_id\n" +
                        "FROM proj_1.nurse as n\n" +
                        "where dep_name='"+this.pdep.getSelectedItem()+"'and (select count (*) from proj_1.patient as p where n.emp_id=p.emp_id)<3";
            String qry2 ="select count (*)\n" +
                            "from proj_1.patient\n" +
                                "where dep_name='"+this.pdep.getSelectedItem()+"'"; 
            Statement stmt=con.createStatement();
             ResultSet rs= stmt.executeQuery(qry2);
             while(rs.next()){ 
            count=rs.getInt(1);
            System.out.println(count);
                    }
             if(count==6){
             JOptionPane.showMessageDialog(null, "The "+this.pdep.getSelectedItem()+" Department is full and can't accept more patients!");
             return;
             }
            rs= stmt.executeQuery(qry);
            while(rs.next()){ 
            nurse_id=rs.getString(1);
            System.out.println(nurse_id);
                    }
            
            qry2="select count (*)\n" +
                            "from proj_1.patient\n" +
                                "where emp_id='"+nurse_id+"'"; 
            rs= stmt.executeQuery(qry2);
            while(rs.next()){ 
            count2=rs.getInt(1);
            System.out.println(count);
                    }
            if(count2>=3)
            {
            JOptionPane.showMessageDialog(null, "The "+this.pdep.getSelectedItem()+" has a shortage of nurses and can't accept more patients!");
             return;
            }
            String pattern = "yyyy-MM-dd";
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern(pattern);

            String date = LocalDate.now().format(formatter);
            String qry3="insert into proj_1.patient values ('"+this.pid.getText()+"','"
                    +this.pfname.getText()+"','"+this.pmname.getText()+"','"+
                    this.plname.getText()+"','"+this.psex.getSelectedItem()+"','"+
                    this.pblood.getSelectedItem()+"','"+this.pyear.getText()+"-"+
                    this.pmonth.getText()+"-"+this.pday.getText()+"','"+this.pnum.getText()+"','"
                    +this.pdep.getSelectedItem()+"','"+nurse_id+"','"+city+"', '"+date+"', null)";
            stmt.executeUpdate(qry3);
            con.commit();
            con.close();
            JOptionPane.showMessageDialog(null, "Done");
        } catch (Exception ex) {
            //Logger.getLogger(ayo.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(null,ex.toString());
            
        }       
    }//GEN-LAST:event_ConfirmAdditionPatientButtonActionPerformed

    private void pass_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_txtActionPerformed

    private void id_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_id_txtFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_id_txtFocusGained

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
       // temp_add.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame temp= new JFrame();
                new add(temp).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmAdditionPatientButton;
    private javax.swing.JLabel Specialty;
    private javax.swing.JTextField Specialty_txt;
    private javax.swing.JTextField address_txt;
    private javax.swing.JTextField beds_txt;
    private javax.swing.JComboBox<String> city_box;
    private javax.swing.JTextField day_txt;
    private javax.swing.JLabel dep;
    private javax.swing.JComboBox<String> dep_box;
    private javax.swing.JTextField dep_name_txt;
    private javax.swing.JComboBox<String> floor;
    private javax.swing.JTextField fname_txt;
    private javax.swing.JTextField id_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField lname_txt;
    private javax.swing.JTextField mname_txt;
    private javax.swing.JTextField month_txt;
    private javax.swing.JTextField pass_txt;
    private javax.swing.JComboBox<String> pblood;
    private javax.swing.JTextField pcity;
    private javax.swing.JComboBox<String> pcitybox;
    private javax.swing.JTextField pday;
    private javax.swing.JComboBox<String> pdep;
    private javax.swing.JTextField pfname;
    private javax.swing.JTextField phone_txt;
    private javax.swing.JTextField pid;
    private javax.swing.JTextField plname;
    private javax.swing.JTextField pmname;
    private javax.swing.JTextField pmonth;
    private javax.swing.JTextField pnum;
    private javax.swing.JComboBox<String> psex;
    private javax.swing.JTextField pyear;
    private javax.swing.JTextField salary_txt;
    private javax.swing.JComboBox<String> sex_box;
    private javax.swing.JComboBox<String> shift_box;
    private javax.swing.JComboBox<String> type_box;
    private javax.swing.JTextField year_txt;
    // End of variables declaration//GEN-END:variables
}
