/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JFrame;

/**
 *
 * @author momo
 */
public class Diagnose extends javax.swing.JFrame {

    /**
     * Creates new form Diagnose
     */
    public static JFrame temp_diagnose;
    public Diagnose(JFrame parent) {
        initComponents();
        this.setResizable(false); 
        this.setLocationRelativeTo(null);
        temp_diagnose=parent;
//        this.hidden.setText(id);
//        this.hidden2.setText(id2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        hidden = new javax.swing.JLabel();
        hidden2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(688, 370));
        setSize(new java.awt.Dimension(688, 318));

        jPanel1.setBackground(new java.awt.Color(217, 244, 255));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 204, 102));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter diagnosis");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 50, 180, 20);

        jButton2.setBackground(new java.awt.Color(153, 204, 255));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Confirm");
        jButton2.setPreferredSize(new java.awt.Dimension(80, 23));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(430, 290, 100, 26);

        jButton3.setBackground(new java.awt.Color(255, 204, 153));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Go Back");
        jButton3.setPreferredSize(new java.awt.Dimension(80, 23));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(560, 290, 100, 26);

        jCheckBox1.setBackground(new java.awt.Color(255, 204, 153));
        jCheckBox1.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setText("Initial diagnosis?");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(40, 220, 140, 30);

        jTextArea1.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 80, 540, 120);

        hidden.setText("jLabel2");
        jPanel1.add(hidden);
        hidden.setBounds(530, 160, 37, 16);

        hidden2.setText("jLabel2");
        jPanel1.add(hidden2);
        hidden2.setBounds(530, 180, 37, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        temp_diagnose.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            DriverManager.registerDriver(new org.postgresql.Driver());
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo,"hmd","0000");
            con.setAutoCommit(false);
            String diagnosis;
            DateTimeFormatter dtf= DateTimeFormatter.ofPattern("yyyy/MM/dd");
            LocalDateTime now = LocalDateTime.now();
            //dtf.format(now);
            String qry="select fname,mname,lname from proj_1.employee where emp_id='"+login.EmpID+"'";
            String qry2="";
            String name="";
            int flag=0;
            Statement stmt=con.createStatement();
            ResultSet rs= stmt.executeQuery(qry);
            while(rs.next()){
                name="Dr. "+rs.getString(1)+" "+rs.getString(3)+"";
            }
            String qry3="select count (*) from proj_1.diagnosis where doc_id='"+login.EmpID+"' and id_no='"+interface_one.PatientID+"'";
            rs=stmt.executeQuery(qry3);
             while(rs.next()){
                 flag=rs.getInt(1);
                 System.out.println(flag);
            }
            if(this.jCheckBox1.isSelected()){
                    diagnosis = ""+dtf.format(now)+"--Inital diagnosis: "+this.jTextArea1.getText()+"---Diagnosed by "+name+"";
                    qry2="insert into proj_1.diagnosis(id_no,doc_id,description,status) values( '"+interface_one.PatientID+"','"+login.EmpID+"','"+diagnosis+"\n','false')";
                }
            else{
                diagnosis =""+dtf.format(now)+"--"+this.jTextArea1.getText()+"---Diagnosed by "+name+"";
                if(flag!=0){
                    qry2="update proj_1.diagnosis set description= description || '"+diagnosis+"\n' where id_no='"+interface_one.PatientID+"' and doc_id='"+login.EmpID+"'";}
                else{
                    qry2="insert into proj_1.diagnosis(id_no,doc_id,description,status) values( '"+interface_one.PatientID+"','"+login.EmpID+"','"+diagnosis+"\n','false')";}
            }
            stmt.executeUpdate(qry2);
            con.commit();
            con.close();
            JOptionPane.showMessageDialog(null, "Done");
            temp_diagnose.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            //Logger.getLogger(ayo.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(null,ex.toString());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diagnose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diagnose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diagnose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diagnose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                String id_temp=null;
//                String id_temp2=null;
                    JFrame temp = new JFrame();
                new Diagnose(temp).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hidden;
    private javax.swing.JLabel hidden2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
