/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.project;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author momo
 */
public class edit_patient extends javax.swing.JFrame {

    /**
     * Creates new form edit_patient
     */
    public edit_patient(ArrayList<String> data) {
        initComponents();
                this.setResizable(false); 
        this.setLocationRelativeTo(null);
        try {
            DriverManager.registerDriver(new org.postgresql.Driver());
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo,"hmd","0000");
            String sql="select dep_name from proj_1.department";
            Statement stmt=con.createStatement();
            ResultSet rs= stmt.executeQuery(sql);
            this.pdep.removeAllItems();
            while(rs.next()){
                String depname=rs.getString(1);
                this.pdep.addItem(depname);
            }
            con.close();
    } catch (Exception ex) {
            //Logger.getLogger(ayo.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(null,ex.toString());
        }
        this.pid.setText(data.get(0).trim());
        this.hidden.setText(data.get(0).trim());
        this.pfname.setText(data.get(1));
        this.pmname.setText(data.get(2));
        this.plname.setText(data.get(3));
        this.psex.setSelectedItem(data.get(4));
        this.pblood.setSelectedItem(data.get(5));
        String date[]=data.get(6).split("-");
        this.pyear.setText(date[0]);
        this.pmonth.setText(date[1]);
        this.pday.setText(date[2]);
        this.pnum.setText(data.get(7));
        String [] cities={"Tulkarm","Jenin","Gaza","Nablus","Jerusalem","Qalqilya","Jericho","Hebron","Bethlehem","Ramallah"};
        int flag=1;
        for(int z=0;z<10;z++){
        if(data.get(10).equals(cities[z])){
            this.pcity.setText("city");
            this.pcitybox.setSelectedItem(data.get(10));
            flag=0;}
        else if (flag==1){
            this.pcity.setText(data.get(10));
            this.pcitybox.setSelectedItem("Other");}
        }
        this.pdep.setSelectedItem(data.get(8));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        pid = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        pfname = new javax.swing.JTextField();
        pmname = new javax.swing.JTextField();
        plname = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        psex = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        pblood = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        pyear = new javax.swing.JTextField();
        pmonth = new javax.swing.JTextField();
        pday = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        pnum = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        pcitybox = new javax.swing.JComboBox<>();
        pcity = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        pdep = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        hidden = new javax.swing.JLabel();
        hidden2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(780, 575));
        setResizable(false);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(217, 244, 255));
        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(null);

        jLabel13.setBackground(new java.awt.Color(255, 204, 102));
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("ID");
        jLabel13.setOpaque(true);
        jPanel1.add(jLabel13);
        jLabel13.setBounds(440, 70, 88, 21);

        pid.setBackground(new java.awt.Color(204, 204, 204));
        pid.setForeground(new java.awt.Color(0, 0, 0));
        pid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(pid);
        pid.setBounds(560, 70, 156, 22);

        jLabel14.setBackground(new java.awt.Color(255, 204, 102));
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Name");
        jLabel14.setOpaque(true);
        jPanel1.add(jLabel14);
        jLabel14.setBounds(20, 70, 88, 21);

        pfname.setBackground(new java.awt.Color(204, 204, 204));
        pfname.setForeground(new java.awt.Color(0, 0, 0));
        pfname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pfname.setText("First Name");
        pfname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pfnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pfnameFocusLost(evt);
            }
        });
        jPanel1.add(pfname);
        pfname.setBounds(140, 70, 150, 22);

        pmname.setBackground(new java.awt.Color(204, 204, 204));
        pmname.setForeground(new java.awt.Color(0, 0, 0));
        pmname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pmname.setText("Middle Name");
        pmname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pmnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pmnameFocusLost(evt);
            }
        });
        jPanel1.add(pmname);
        pmname.setBounds(140, 100, 150, 22);

        plname.setBackground(new java.awt.Color(204, 204, 204));
        plname.setForeground(new java.awt.Color(0, 0, 0));
        plname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        plname.setText("Last Name");
        plname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                plnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                plnameFocusLost(evt);
            }
        });
        jPanel1.add(plname);
        plname.setBounds(140, 130, 150, 22);

        jLabel15.setBackground(new java.awt.Color(255, 204, 102));
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Sex");
        jLabel15.setOpaque(true);
        jPanel1.add(jLabel15);
        jLabel15.setBounds(20, 230, 88, 21);

        psex.setBackground(new java.awt.Color(204, 204, 204));
        psex.setForeground(new java.awt.Color(0, 0, 0));
        psex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        jPanel1.add(psex);
        psex.setBounds(140, 230, 55, 22);

        jLabel16.setBackground(new java.awt.Color(255, 204, 102));
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("BLood Type");
        jLabel16.setOpaque(true);
        jPanel1.add(jLabel16);
        jLabel16.setBounds(440, 120, 88, 21);

        pblood.setBackground(new java.awt.Color(204, 204, 204));
        pblood.setForeground(new java.awt.Color(0, 0, 0));
        pblood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        jPanel1.add(pblood);
        pblood.setBounds(560, 120, 57, 22);

        jLabel17.setBackground(new java.awt.Color(255, 204, 102));
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Birth Date");
        jLabel17.setOpaque(true);
        jPanel1.add(jLabel17);
        jLabel17.setBounds(20, 180, 88, 21);

        pyear.setBackground(new java.awt.Color(204, 204, 204));
        pyear.setForeground(new java.awt.Color(0, 0, 0));
        pyear.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pyear.setText("YYYY");
        pyear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pyearFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pyearFocusLost(evt);
            }
        });
        jPanel1.add(pyear);
        pyear.setBounds(140, 180, 71, 22);

        pmonth.setBackground(new java.awt.Color(204, 204, 204));
        pmonth.setForeground(new java.awt.Color(0, 0, 0));
        pmonth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pmonth.setText("MM");
        pmonth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pmonthFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pmonthFocusLost(evt);
            }
        });
        jPanel1.add(pmonth);
        pmonth.setBounds(220, 180, 71, 22);

        pday.setBackground(new java.awt.Color(204, 204, 204));
        pday.setForeground(new java.awt.Color(0, 0, 0));
        pday.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pday.setText("DD");
        pday.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pdayFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pdayFocusLost(evt);
            }
        });
        jPanel1.add(pday);
        pday.setBounds(300, 180, 71, 22);

        jLabel18.setBackground(new java.awt.Color(255, 204, 102));
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Phone Number");
        jLabel18.setOpaque(true);
        jPanel1.add(jLabel18);
        jLabel18.setBounds(20, 330, 88, 21);

        pnum.setBackground(new java.awt.Color(204, 204, 204));
        pnum.setForeground(new java.awt.Color(0, 0, 0));
        pnum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(pnum);
        pnum.setBounds(140, 330, 148, 22);

        jLabel19.setBackground(new java.awt.Color(255, 204, 102));
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Address");
        jLabel19.setOpaque(true);
        jPanel1.add(jLabel19);
        jLabel19.setBounds(20, 280, 88, 21);

        pcitybox.setBackground(new java.awt.Color(204, 204, 204));
        pcitybox.setForeground(new java.awt.Color(0, 0, 0));
        pcitybox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tulkarm", "Jenin", "Gaza", "Nablus", "Jerusalem", "Qalqilya", "Jericho", "Hebron", "Bethlehem", "Ramallah", "Other" }));
        pcitybox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcityboxActionPerformed(evt);
            }
        });
        jPanel1.add(pcitybox);
        pcitybox.setBounds(140, 280, 91, 22);

        pcity.setEditable(false);
        pcity.setBackground(new java.awt.Color(204, 204, 204));
        pcity.setForeground(new java.awt.Color(102, 102, 102));
        pcity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pcity.setText("City");
        pcity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pcityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pcityFocusLost(evt);
            }
        });
        jPanel1.add(pcity);
        pcity.setBounds(250, 280, 136, 22);

        jLabel20.setBackground(new java.awt.Color(255, 204, 102));
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Department");
        jLabel20.setOpaque(true);
        jPanel1.add(jLabel20);
        jLabel20.setBounds(440, 170, 88, 21);

        pdep.setBackground(new java.awt.Color(204, 204, 204));
        pdep.setForeground(new java.awt.Color(0, 0, 0));
        pdep.setOpaque(true);
        jPanel1.add(pdep);
        pdep.setBounds(560, 170, 120, 22);

        jButton1.setBackground(new java.awt.Color(255, 204, 153));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Go Back");
        jButton1.setAlignmentX(1.0F);
        jButton1.setAlignmentY(1.0F);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(530, 480, 170, 40);

        jButton2.setBackground(new java.awt.Color(153, 204, 255));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(110, 480, 170, 40);

        jButton3.setBackground(new java.awt.Color(255, 102, 102));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Delete");
        jButton3.setAlignmentX(1.0F);
        jButton3.setAlignmentY(1.0F);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(320, 480, 170, 40);

        hidden.setText("jLabel1");
        jPanel1.add(hidden);
        hidden.setBounds(50, 70, 37, 16);

        hidden2.setText("jLabel1");
        jPanel1.add(hidden2);
        hidden2.setBounds(50, 180, 37, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pfnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfnameFocusGained
        // TODO add your handling code here:
        if (pfname.getText().equals("First Name")) {
            pfname.setText("");
        pfname.setForeground(Color.black);}
    }//GEN-LAST:event_pfnameFocusGained

    private void pfnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfnameFocusLost
        // TODO add your handling code here:
        if (pfname.getText().isEmpty()) {
            pfname.setText("First Name");
        pfname.setForeground(Color.GRAY);}

    }//GEN-LAST:event_pfnameFocusLost

    private void pmnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pmnameFocusGained
        // TODO add your handling code here:
        if (pmname.getText().equals("Middle Name")) {
            pmname.setText("");
         pmname.setForeground(Color.black);}
    }//GEN-LAST:event_pmnameFocusGained

    private void pmnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pmnameFocusLost
        // TODO add your handling code here:
        if (pmname.getText().isEmpty()) {
            pmname.setText("Middle Name");
        pmname.setForeground(Color.GRAY);}
    }//GEN-LAST:event_pmnameFocusLost

    private void plnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_plnameFocusGained
        // TODO add your handling code here:
        if (plname.getText().equals("Last Name")) {
            plname.setText("");
        plname.setForeground(Color.black);}
    }//GEN-LAST:event_plnameFocusGained

    private void plnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_plnameFocusLost
        // TODO add your handling code here:
        if (plname.getText().isEmpty()) {
            plname.setText("Last Name");
        plname.setForeground(Color.GRAY);}
    }//GEN-LAST:event_plnameFocusLost

    private void pyearFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pyearFocusGained
        // TODO add your handling code here:
        if (pyear.getText().equals("YYYY")) {
            pyear.setText("");
        pyear.setForeground(Color.black);}
    }//GEN-LAST:event_pyearFocusGained

    private void pyearFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pyearFocusLost
        // TODO add your handling code here:
        if (pyear.getText().isEmpty()) {
            pyear.setText("YYYY");
        pyear.setForeground(Color.GRAY);}
    }//GEN-LAST:event_pyearFocusLost

    private void pmonthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pmonthFocusGained
        // TODO add your handling code here:
        if (pmonth.getText().equals("MM")) {
            pmonth.setText("");
        pmonth.setForeground(Color.black);}
    }//GEN-LAST:event_pmonthFocusGained

    private void pmonthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pmonthFocusLost
        // TODO add your handling code here:
        if (pmonth.getText().isEmpty()) {
            pmonth.setText("MM");
        pmonth.setForeground(Color.GRAY);}
    }//GEN-LAST:event_pmonthFocusLost

    private void pdayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pdayFocusGained
        // TODO add your handling code here:
        if (pday.getText().equals("DD")) {
            pday.setText("");
        pday.setForeground(Color.black);}
    }//GEN-LAST:event_pdayFocusGained

    private void pdayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pdayFocusLost
        // TODO add your handling code here:
        if (pday.getText().isEmpty()) {
            pday.setText("DD");
        pday.setForeground(Color.GRAY);}
    }//GEN-LAST:event_pdayFocusLost

    private void pcityboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcityboxActionPerformed
        // TODO add your handling code here:
        if(this.pcitybox.getSelectedItem().equals("Other")){
            this.pcity.setEditable(true);
            this.pcity.setForeground(Color.black);}
        else{
            this.pcity.setEditable(false);
            this.pcity.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_pcityboxActionPerformed

    private void pcityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pcityFocusGained
        // TODO add your handling code here:
        if (pcity.getText().equals("City")&&(pcity.isEditable()==true)) {
            pcity.setText("");}
    }//GEN-LAST:event_pcityFocusGained

    private void pcityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pcityFocusLost
        // TODO add your handling code here:
        if (pcity.getText().isEmpty()) {
            pcity.setText("City");
        }
    }//GEN-LAST:event_pcityFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new search(this).setVisible(true);
        search.setSelectedTab(2);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            DriverManager.registerDriver(new org.postgresql.Driver());
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo,"hmd","0000");
            con.setAutoCommit(false);
            String city=this.pcitybox.getSelectedItem().toString();
            if(this.pcitybox.getSelectedItem().equals("Other")){
                city=this.pcity.getText();}
            String qry=null;
            String qry1=null;
            String qry2=null;
            String qry3=null;
            String qry_temp="";
            String qry_temp2="";
            int flag=0;
            if(this.hidden.getText().equals(this.pid.getText())){
            qry="update proj_1.patient set fname='"+this.pfname.getText()+"', mname='"+this.pmname.getText()+"',lname='"+this.plname.getText()+"',sex='"+this.psex.getSelectedItem()+"',blood_type='"+this.pblood.getSelectedItem()+"',bdate='"+this.pyear.getText()+"-"+this.pmonth.getText()+"-"+this.pday.getText()+"',phone_number='"+this.pnum.getText()+"',dep_name='"+this.pdep.getSelectedItem()+"',address='"+city+"' where id_no='"+this.pid.getText()+"'";
            }
            else{
            qry="insert into proj_1.patient values ('"+this.pid.getText()+"','"+this.pfname.getText()+"','"+this.pmname.getText()+"','"+this.plname.getText()+"','"+this.psex.getSelectedItem()+"','"+this.pblood.getSelectedItem()+"','"+this.pyear.getText()+"-"+this.pmonth.getText()+"-"+this.pday.getText()+"','"+this.pnum.getText()+"','"+this.pdep.getSelectedItem()+"',null,'"+city+"')";
            qry2="update proj_1.diagnosis set id_no='"+this.pid.getText()+"' where id_no='"+this.hidden.getText()+"'";
            qry_temp="update proj_1.nurse_tech set pid = '"+this.pid.getText()+"' where tech_id='"+this.hidden.getText()+"'";
            qry_temp2="update proj_1.orders set \"patient_ID\"='"+this.pid.getText()+"' where \"patient_ID\" = '"+this.hidden.getText()+"'";
            qry3="delete from proj_1.patient where id_no='"+this.hidden.getText()+"'";
            flag=1;
            }
            Statement stmt=con.createStatement();
            stmt.executeUpdate(qry);
            if(flag==1){
            stmt.executeUpdate(qry2);
            stmt.executeUpdate(qry_temp);
            stmt.executeUpdate(qry_temp2);
            stmt.executeUpdate(qry3);}
            con.commit();
            con.close();
            JOptionPane.showMessageDialog(null, "Done");
            new search(this).setVisible(true);
            search.setSelectedTab(2);
            this.dispose();
        } catch (Exception ex) {
            //Logger.getLogger(ayo.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(null,ex.toString());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPanel1FocusGained

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jPanel1MouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formComponentShown

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            DriverManager.registerDriver(new org.postgresql.Driver());
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo,"hmd","0000");
            con.setAutoCommit(false);
            String qry=null;
            String qry2=null;
            String qry3=null;
            String qry4=null;
            qry="delete from proj_1.diagnosis where id_no='"+this.pid.getText()+"'";
            qry2="delete from proj_1.patient where id_no='"+this.pid.getText()+"'";
            qry3="update proj_1.nurse_tech set pid=null where pid='"+this.pid.getText()+"'";
            qry4="update proj_1.orders set \"patient_ID\"=null where \"patient_ID\"='"+this.pid.getText()+"'";
            Statement stmt=con.createStatement();
            stmt.executeUpdate(qry);
            stmt.executeUpdate(qry2);
            stmt.executeUpdate(qry3);
            stmt.executeUpdate(qry4);
            con.commit();
            con.close();
            JOptionPane.showMessageDialog(null, "Done");
        } catch (Exception ex) {
            //Logger.getLogger(ayo.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(null,ex.toString());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ArrayList<String> temp = new ArrayList<>();
                new edit_patient(temp).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hidden;
    private javax.swing.JLabel hidden2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> pblood;
    private javax.swing.JTextField pcity;
    private javax.swing.JComboBox<String> pcitybox;
    private javax.swing.JTextField pday;
    private javax.swing.JComboBox<String> pdep;
    private javax.swing.JTextField pfname;
    private javax.swing.JTextField pid;
    private javax.swing.JTextField plname;
    private javax.swing.JTextField pmname;
    private javax.swing.JTextField pmonth;
    private javax.swing.JTextField pnum;
    private javax.swing.JComboBox<String> psex;
    private javax.swing.JTextField pyear;
    // End of variables declaration//GEN-END:variables
}
