/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.project;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author momo
 */
public class edit_emp extends javax.swing.JFrame {

    /**
     * Creates new form view_edit
     * @param data
     */
    
    public edit_emp(ArrayList<String> data) {
        initComponents();
                this.setResizable(false); 
        this.setLocationRelativeTo(null);
        try {
            DriverManager.registerDriver(new org.postgresql.Driver());
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo,"hmd","0000");
            String sql="select dep_name from proj_1.department";
            Statement stmt=con.createStatement();
            ResultSet rs= stmt.executeQuery(sql);
            this.dep_box.removeAllItems();
            while(rs.next()){
                String depname=rs.getString(1);
                this.dep_box.addItem(depname);
            }
            con.close();
    } catch (Exception ex) {
            //Logger.getLogger(ayo.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(null,ex.toString());
        }
        this.id_txt.setText(data.get(0).trim());
        this.hidden.setText(data.get(0).trim());
        this.fname_txt.setText(data.get(1));
        this.mname_txt.setText(data.get(2));
        this.lname_txt.setText(data.get(3));
        this.sex_box.setSelectedItem(data.get(4));
        String date[]=data.get(5).split("-");
        this.year_txt.setText(date[0]);
        this.month_txt.setText(date[1]);
        this.day_txt.setText(date[2]);
        this.phone_txt.setText(data.get(6));
        this.salary_txt.setText(data.get(7));
        this.shift_box.setSelectedItem(data.get(8));
        String [] cities={"Tulkarm","Jenin","Gaza","Nablus","Jerusalem","Qalqilya","Jericho","Hebron","Bethlehem","Ramallah"};
        loop: for(int z=0;z<10;z++){
        if(data.get(9).equals(cities[z])){
            this.address_txt.setText("city");
            this.city_box.setSelectedItem(data.get(9));
            break loop;}
        else{
            this.address_txt.setText(data.get(9));
            this.city_box.setSelectedItem("Other");}
        }
        this.type_box.setSelectedItem(data.get(10));
        this.hidden2.setText(data.get(10));
        if(data.get(10).equals("Doctor")|| data.get(10).equals("Nurse")){
        this.dep_box.setSelectedItem(data.get(11));}
        if(data.get(10).equals("Doctor")){
        this.Specialty_txt.setText(data.get(12));}
        for (String element : data) {
            System.out.println(element);
            
        }
        this.pass_txt.setText(data.get(13));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        city_box = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        shift_box = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        salary_txt = new javax.swing.JTextField();
        address_txt = new javax.swing.JTextField();
        lname_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        id_txt = new javax.swing.JTextField();
        sex_box = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        phone_txt = new javax.swing.JTextField();
        day_txt = new javax.swing.JTextField();
        fname_txt = new javax.swing.JTextField();
        month_txt = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        year_txt = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        Specialty_txt = new javax.swing.JTextField();
        mname_txt = new javax.swing.JTextField();
        Specialty = new javax.swing.JLabel();
        dep_box = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        dep = new javax.swing.JLabel();
        type_box = new javax.swing.JComboBox<>();
        pass_txt = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        hidden = new javax.swing.JLabel();
        hidden2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(780, 575));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(217, 244, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(659, 535));
        jPanel1.setLayout(null);

        city_box.setBackground(new java.awt.Color(204, 204, 204));
        city_box.setForeground(new java.awt.Color(0, 0, 0));
        city_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tulkarm", "Jenin", "Gaza", "Nablus", "Jerusalem", "Qalqilya", "Jericho", "Hebron", "Bethlehem", "Ramallah", "Other" }));
        city_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                city_boxActionPerformed(evt);
            }
        });
        jPanel1.add(city_box);
        city_box.setBounds(140, 280, 91, 22);

        jLabel6.setBackground(new java.awt.Color(255, 204, 102));
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Birth Date");
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 180, 88, 21);

        jLabel10.setBackground(new java.awt.Color(255, 204, 102));
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Address");
        jLabel10.setOpaque(true);
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 280, 88, 21);

        jLabel3.setBackground(new java.awt.Color(255, 204, 102));
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Employee Type");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(440, 170, 88, 21);

        shift_box.setBackground(new java.awt.Color(204, 204, 204));
        shift_box.setForeground(new java.awt.Color(0, 0, 0));
        shift_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C" }));
        shift_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shift_boxActionPerformed(evt);
            }
        });
        jPanel1.add(shift_box);
        shift_box.setBounds(560, 270, 45, 22);

        jLabel8.setBackground(new java.awt.Color(255, 204, 102));
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Salary");
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(440, 220, 88, 21);

        salary_txt.setBackground(new java.awt.Color(204, 204, 204));
        salary_txt.setForeground(new java.awt.Color(0, 0, 0));
        salary_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(salary_txt);
        salary_txt.setBounds(560, 220, 70, 22);

        address_txt.setEditable(false);
        address_txt.setBackground(new java.awt.Color(204, 204, 204));
        address_txt.setForeground(new java.awt.Color(102, 102, 102));
        address_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        address_txt.setText("City");
        address_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                address_txtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                address_txtFocusLost(evt);
            }
        });
        address_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address_txtActionPerformed(evt);
            }
        });
        jPanel1.add(address_txt);
        address_txt.setBounds(250, 280, 136, 22);

        lname_txt.setBackground(new java.awt.Color(204, 204, 204));
        lname_txt.setForeground(new java.awt.Color(0, 0, 0));
        lname_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lname_txt.setText("Last Name");
        lname_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lname_txtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lname_txtFocusLost(evt);
            }
        });
        jPanel1.add(lname_txt);
        lname_txt.setBounds(140, 130, 150, 22);

        jLabel2.setBackground(new java.awt.Color(255, 204, 102));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ID");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(440, 70, 88, 21);

        jLabel4.setBackground(new java.awt.Color(255, 204, 102));
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Name");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 70, 88, 21);

        id_txt.setBackground(new java.awt.Color(204, 204, 204));
        id_txt.setForeground(new java.awt.Color(0, 0, 0));
        id_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        id_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_txtActionPerformed(evt);
            }
        });
        jPanel1.add(id_txt);
        id_txt.setBounds(560, 70, 156, 22);

        sex_box.setBackground(new java.awt.Color(204, 204, 204));
        sex_box.setForeground(new java.awt.Color(0, 0, 0));
        sex_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F", " " }));
        jPanel1.add(sex_box);
        sex_box.setBounds(140, 230, 55, 22);

        jLabel5.setBackground(new java.awt.Color(255, 204, 102));
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Sex");
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 230, 88, 21);

        jLabel9.setBackground(new java.awt.Color(255, 204, 102));
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Shift");
        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9);
        jLabel9.setBounds(440, 270, 88, 21);

        phone_txt.setBackground(new java.awt.Color(204, 204, 204));
        phone_txt.setForeground(new java.awt.Color(0, 0, 0));
        phone_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(phone_txt);
        phone_txt.setBounds(140, 330, 148, 22);

        day_txt.setBackground(new java.awt.Color(204, 204, 204));
        day_txt.setForeground(new java.awt.Color(0, 0, 0));
        day_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        day_txt.setText("DD");
        day_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                day_txtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                day_txtFocusLost(evt);
            }
        });
        jPanel1.add(day_txt);
        day_txt.setBounds(300, 180, 71, 22);

        fname_txt.setBackground(new java.awt.Color(204, 204, 204));
        fname_txt.setForeground(new java.awt.Color(0, 0, 0));
        fname_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fname_txt.setText("First Name");
        fname_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fname_txtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fname_txtFocusLost(evt);
            }
        });
        fname_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fname_txtActionPerformed(evt);
            }
        });
        jPanel1.add(fname_txt);
        fname_txt.setBounds(140, 70, 150, 22);

        month_txt.setBackground(new java.awt.Color(204, 204, 204));
        month_txt.setForeground(new java.awt.Color(0, 0, 0));
        month_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        month_txt.setText("MM");
        month_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                month_txtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                month_txtFocusLost(evt);
            }
        });
        jPanel1.add(month_txt);
        month_txt.setBounds(220, 180, 71, 22);

        jButton2.setBackground(new java.awt.Color(153, 204, 255));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(110, 480, 170, 40);

        jButton1.setBackground(new java.awt.Color(255, 204, 153));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Go Back");
        jButton1.setAlignmentX(1.0F);
        jButton1.setAlignmentY(1.0F);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(530, 480, 170, 40);

        year_txt.setBackground(new java.awt.Color(204, 204, 204));
        year_txt.setForeground(new java.awt.Color(0, 0, 0));
        year_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        year_txt.setText("YYYY");
        year_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                year_txtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                year_txtFocusLost(evt);
            }
        });
        jPanel1.add(year_txt);
        year_txt.setBounds(140, 180, 71, 22);

        jButton3.setBackground(new java.awt.Color(255, 102, 102));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Delete");
        jButton3.setAlignmentX(1.0F);
        jButton3.setAlignmentY(1.0F);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(320, 480, 170, 40);

        Specialty_txt.setBackground(new java.awt.Color(204, 204, 204));
        Specialty_txt.setForeground(new java.awt.Color(0, 0, 0));
        Specialty_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Specialty_txt.setToolTipText("");
        jPanel1.add(Specialty_txt);
        Specialty_txt.setBounds(140, 380, 136, 22);

        mname_txt.setBackground(new java.awt.Color(204, 204, 204));
        mname_txt.setForeground(new java.awt.Color(0, 0, 0));
        mname_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mname_txt.setText("Middle Name");
        mname_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mname_txtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mname_txtFocusLost(evt);
            }
        });
        jPanel1.add(mname_txt);
        mname_txt.setBounds(140, 100, 150, 22);

        Specialty.setBackground(new java.awt.Color(255, 204, 102));
        Specialty.setForeground(new java.awt.Color(0, 0, 0));
        Specialty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Specialty.setText("Specialty");
        Specialty.setOpaque(true);
        jPanel1.add(Specialty);
        Specialty.setBounds(20, 380, 88, 21);

        dep_box.setBackground(new java.awt.Color(204, 204, 204));
        dep_box.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(dep_box);
        dep_box.setBounds(560, 320, 120, 22);

        jLabel7.setBackground(new java.awt.Color(255, 204, 102));
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Phone Number");
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 330, 88, 21);

        dep.setBackground(new java.awt.Color(255, 204, 102));
        dep.setForeground(new java.awt.Color(0, 0, 0));
        dep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dep.setText("Department");
        dep.setOpaque(true);
        jPanel1.add(dep);
        dep.setBounds(440, 320, 88, 21);

        type_box.setBackground(new java.awt.Color(204, 204, 204));
        type_box.setForeground(new java.awt.Color(0, 0, 0));
        type_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Doctor", "Nurse", "Lab Technician" }));
        type_box.setEnabled(false);
        type_box.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                type_boxComponentHidden(evt);
            }
        });
        type_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type_boxActionPerformed(evt);
            }
        });
        jPanel1.add(type_box);
        type_box.setBounds(560, 170, 119, 22);

        pass_txt.setBackground(new java.awt.Color(204, 204, 204));
        pass_txt.setForeground(new java.awt.Color(0, 0, 0));
        pass_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pass_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_txtActionPerformed(evt);
            }
        });
        jPanel1.add(pass_txt);
        pass_txt.setBounds(560, 120, 156, 22);

        jLabel21.setBackground(new java.awt.Color(255, 204, 102));
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Password");
        jLabel21.setOpaque(true);
        jPanel1.add(jLabel21);
        jLabel21.setBounds(440, 120, 88, 21);

        hidden.setText("jLabel24");
        jPanel1.add(hidden);
        hidden.setBounds(40, 70, 43, 16);

        hidden2.setText("jLabel24");
        jPanel1.add(hidden2);
        hidden2.setBounds(40, 180, 43, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void type_boxComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_type_boxComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_type_boxComponentHidden

    private void type_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type_boxActionPerformed
        // TODO add your handling code here:
        if(this.type_box.getSelectedItem().equals("Doctor")){
            this.dep_box.setVisible(true);
            this.dep.setVisible(true);
            this.Specialty_txt.setVisible(true);
            this.Specialty.setVisible(true);
        }
        if(this.type_box.getSelectedItem().equals("Nurse")){
            this.dep_box.setVisible(true);
            this.dep.setVisible(true);
            this.Specialty_txt.setVisible(false);
            this.Specialty.setVisible(false);
        }
        if(this.type_box.getSelectedItem().equals("Lab Technician")){
            this.dep_box.setVisible(false);
            this.dep.setVisible(false);
            this.Specialty_txt.setVisible(false);
            this.Specialty.setVisible(false);
        }

    }//GEN-LAST:event_type_boxActionPerformed

    private void id_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_txtActionPerformed

    private void fname_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fname_txtFocusGained
        // TODO add your handling code here:
        if (fname_txt.getText().equals("First Name")) {
            fname_txt.setForeground(Color.black);
            fname_txt.setText("");}
    }//GEN-LAST:event_fname_txtFocusGained

    private void fname_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fname_txtFocusLost
        // TODO add your handling code here:
        if (fname_txt.getText().isEmpty()) {
            fname_txt.setForeground(Color.gray);
            fname_txt.setText("First Name");
        }
    }//GEN-LAST:event_fname_txtFocusLost

    private void fname_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fname_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fname_txtActionPerformed

    private void mname_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mname_txtFocusGained
        // TODO add your handling code here:
        if (mname_txt.getText().equals("Middle Name")) {
            mname_txt.setForeground(Color.black);
            mname_txt.setText("");}
    }//GEN-LAST:event_mname_txtFocusGained

    private void mname_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mname_txtFocusLost
        // TODO add your handling code here:
        if (mname_txt.getText().isEmpty()) {
            mname_txt.setForeground(Color.gray);
            mname_txt.setText("Middle Name");
        }
    }//GEN-LAST:event_mname_txtFocusLost

    private void lname_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lname_txtFocusGained
        // TODO add your handling code here:
        if (lname_txt.getText().equals("Last Name")) {
            lname_txt.setForeground(Color.black);
            lname_txt.setText("");}
    }//GEN-LAST:event_lname_txtFocusGained

    private void lname_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lname_txtFocusLost
        // TODO add your handling code here:
        if (lname_txt.getText().isEmpty()) {
            lname_txt.setForeground(Color.gray);
            lname_txt.setText("Last Name");
        }
    }//GEN-LAST:event_lname_txtFocusLost

    private void year_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_year_txtFocusGained
        // TODO add your handling code here:
        if (year_txt.getText().equals("YYYY")) {
            year_txt.setText("");}

    }//GEN-LAST:event_year_txtFocusGained

    private void year_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_year_txtFocusLost
        // TODO add your handling code here:
        if (year_txt.getText().isEmpty()) {
            year_txt.setText("YYYY");
        }
    }//GEN-LAST:event_year_txtFocusLost

    private void month_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_month_txtFocusGained
        // TODO add your handling code here:
        if (month_txt.getText().equals("MM")) {
            month_txt.setText("");}
    }//GEN-LAST:event_month_txtFocusGained

    private void month_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_month_txtFocusLost
        // TODO add your handling code here:
        if (month_txt.getText().isEmpty()) {
            month_txt.setText("MM");
        }
    }//GEN-LAST:event_month_txtFocusLost

    private void day_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_day_txtFocusGained
        // TODO add your handling code here:
        if (day_txt.getText().equals("DD")) {
            day_txt.setText("");}
    }//GEN-LAST:event_day_txtFocusGained

    private void day_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_day_txtFocusLost
        // TODO add your handling code here:
        if (day_txt.getText().isEmpty()) {
            day_txt.setText("DD");
        }
    }//GEN-LAST:event_day_txtFocusLost

    private void city_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_city_boxActionPerformed
        // TODO add your handling code here:
        if(this.city_box.getSelectedItem().equals("Other")){
            this.address_txt.setEditable(true);
            this.address_txt.setForeground(Color.black);
        }
        else{
            this.address_txt.setEditable(false);
            this.address_txt.setForeground(Color.GRAY);}
    }//GEN-LAST:event_city_boxActionPerformed

    private void address_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_address_txtFocusGained
        // TODO add your handling code here:
        if (address_txt.getText().equals("City")&&(address_txt.isEditable()==true)) {
            address_txt.setText("");}
    }//GEN-LAST:event_address_txtFocusGained

    private void address_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_address_txtFocusLost
        // TODO add your handling code here:
        if (address_txt.getText().isEmpty()) {
            address_txt.setText("City");
        }
    }//GEN-LAST:event_address_txtFocusLost

    private void address_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address_txtActionPerformed

    private void shift_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shift_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shift_boxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new search(this).setVisible(true);
        search.setSelectedTab(0);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            DriverManager.registerDriver(new org.postgresql.Driver());
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo,"hmd","0000");
            con.setAutoCommit(false);
            String city=this.city_box.getSelectedItem().toString();
            if(this.city_box.getSelectedItem().equals("Other")){
            city=this.address_txt.getText();}
            String qry_update=null;
            String qry_update2=null;
            String qry_update3=null;
            String qry_update4=null;
            String qry_update5=null;
            String qry_update6=null;
            String qry_temp="";
            int flag=0;
            int flag2=0;
            if(this.id_txt.getText().equals(this.hidden.getText()) && (this.hidden2.getText().equals("Doctor")))
            {
              qry_update="update proj_1.employee set fname='"+this.fname_txt.getText()+"',mname='"+this.mname_txt.getText()+"',lname='"+this.lname_txt.getText()+"',sex='"+this.sex_box.getSelectedItem()+"',bdate='"+this.year_txt.getText()+"-"+this.month_txt.getText()+"-"+this.day_txt.getText()+"',phone_number='"+this.phone_txt.getText()+"',salary="+this.salary_txt.getText()+",address='"+city+"',pass_word='"+this.pass_txt.getText()+"' where emp_id='"+this.id_txt.getText()+"'";
              qry_update2="update proj_1.doctor set dep_name='"+this.dep_box.getSelectedItem()+"',specialty='"+this.Specialty_txt.getText()+"', pass_word='"+this.pass_txt.getText()+"' where emp_id='"+this.hidden.getText()+"'"; 
              flag2=1;
            }
            if(this.id_txt.getText().equals(this.hidden.getText()) && (this.hidden2.getText().equals("Nurse")))
            {
              qry_update="update proj_1.employee set fname='"+this.fname_txt.getText()+"',mname='"+this.mname_txt.getText()+"',lname='"+this.lname_txt.getText()+"',sex='"+this.sex_box.getSelectedItem()+"',bdate='"+this.year_txt.getText()+"-"+this.month_txt.getText()+"-"+this.day_txt.getText()+"',phone_number='"+this.phone_txt.getText()+"',salary="+this.salary_txt.getText()+",address='"+city+"',pass_word='"+this.pass_txt.getText()+"' where emp_id='"+this.id_txt.getText()+"'";
              qry_update2="update proj_1.nurse set dep_name='"+this.dep_box.getSelectedItem()+"',pass_word='"+this.pass_txt.getText()+"' where emp_id='"+this.hidden.getText()+"'"; 
              flag2=1;
            }
            if(this.id_txt.getText().equals(this.hidden.getText()) && (this.hidden2.getText().equals("Lab Technician")))
            {
              qry_update="update proj_1.employee set fname='"+this.fname_txt.getText()+"',mname='"+this.mname_txt.getText()+"',lname='"+this.lname_txt.getText()+"',sex='"+this.sex_box.getSelectedItem()+"',bdate='"+this.year_txt.getText()+"-"+this.month_txt.getText()+"-"+this.day_txt.getText()+"',phone_number='"+this.phone_txt.getText()+"',salary="+this.salary_txt.getText()+",address='"+city+"',pass_word='"+this.pass_txt.getText()+"' where emp_id='"+this.id_txt.getText()+"'";
              qry_update2="update proj_1.lab_technician set pass_word='"+this.pass_txt.getText()+"' where emp_id='"+this.id_txt.getText()+"'";
              flag2=1;
            }
            if((!this.id_txt.getText().equals(this.hidden.getText())) && (this.hidden2.getText().equals("Doctor"))){
                   qry_update="update proj_1.employee set emp_id='"+this.id_txt.getText()+"',fname='"+this.fname_txt.getText()+"',mname='"+this.mname_txt.getText()+"',lname='"+this.lname_txt.getText()+"',sex='"+this.sex_box.getSelectedItem()+"',bdate='"+this.year_txt.getText()+"-"+this.month_txt.getText()+"-"+this.day_txt.getText()+"',phone_number='"+this.phone_txt.getText()+"',salary="+this.salary_txt.getText()+",address='"+city+"',pass_word='"+this.pass_txt.getText()+"' where emp_id='"+this.hidden.getText()+"'";
                   qry_update2="update proj_1.doctor set emp_id='"+this.id_txt.getText()+"',dep_name='"+this.dep_box.getSelectedItem()+"',pass_word='"+this.pass_txt.getText()+"', specialty='"+this.Specialty_txt.getText()+"' where emp_id='"+this.hidden.getText()+"'";  
            }
            if((!this.id_txt.getText().equals(this.hidden.getText())) && (this.hidden2.getText().equals("Nurse"))){
                qry_update="update proj_1.employee set emp_id='"+this.id_txt.getText()+"',fname='"+this.fname_txt.getText()+"',mname='"+this.mname_txt.getText()+"',lname='"+this.lname_txt.getText()+"',sex='"+this.sex_box.getSelectedItem()+"',bdate='"+this.year_txt.getText()+"-"+this.month_txt.getText()+"-"+this.day_txt.getText()+"',phone_number='"+this.phone_txt.getText()+"',salary="+this.salary_txt.getText()+",address='"+city+"',pass_word='"+this.pass_txt.getText()+"' where emp_id='"+this.hidden.getText()+"'";
                qry_update2="update proj_1.nurse set emp_id='"+this.id_txt.getText()+"',dep_name='"+this.dep_box.getSelectedItem()+"',pass_word='"+this.pass_txt.getText()+"' where emp_id='"+this.hidden.getText()+"'";
            }
           if((!this.id_txt.getText().equals(this.hidden.getText())) && (this.hidden2.getText().equals("Lab Technician"))){
                qry_update="update proj_1.employee set emp_id='"+this.id_txt.getText()+"',fname='"+this.fname_txt.getText()+"',mname='"+this.mname_txt.getText()+"',lname='"+this.lname_txt.getText()+"',sex='"+this.sex_box.getSelectedItem()+"',bdate='"+this.year_txt.getText()+"-"+this.month_txt.getText()+"-"+this.day_txt.getText()+"',phone_number='"+this.phone_txt.getText()+"',salary="+this.salary_txt.getText()+",address='"+city+"',pass_word='"+this.pass_txt.getText()+"' where emp_id='"+this.hidden.getText()+"'";
                qry_update2="update proj_1.lab_technician set emp_id='"+this.id_txt.getText()+"',pass_word='"+this.pass_txt.getText()+"' where emp_id='"+this.hidden.getText()+"'";
           }
            Statement stmt=con.createStatement();
            stmt.executeUpdate(qry_update);
            stmt.executeUpdate(qry_update2);
            if (flag==1){
            stmt.executeUpdate(qry_update3);
            stmt.executeUpdate(qry_update4);
            stmt.executeUpdate(qry_temp);
            stmt.executeUpdate(qry_update5);
            stmt.executeUpdate(qry_update6);}
            con.commit();
            con.close();
            JOptionPane.showMessageDialog(null, "Done");
            new search(this).setVisible(true);
            search.setSelectedTab(0);
            this.dispose();
        } catch (Exception ex) {
            //Logger.getLogger(ayo.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(null,ex.toString());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            DriverManager.registerDriver(new org.postgresql.Driver());
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo,"hmd","0000");
            con.setAutoCommit(false);
            String qry=null;
            String qry2=null;
            String qry3=null;
            String qry4=null;
            String qry5="";
            if(this.hidden2.getText().equals("Doctor")){
            //qry="delete from proj_1.orders where doc_id='"+this.id_txt.getText()+"'";
            //qry2="update proj_1.diagnosis set doc_id=null where doc_id='"+this.id_txt.getText()+"'";
            //qry5="update proj_1.nurse_tech set doc_id=null where doc_id='"+this.id_txt.getText()+"'";
            qry3="delete from proj_1.doctor where emp_id='"+this.id_txt.getText()+"'";
            qry4="delete from proj_1.employee where emp_id='"+this.id_txt.getText()+"'";
            }
            
            if(this.hidden2.getText().equals("Nurse")){
            //qry="delete from proj_1.orders where nurse_id='"+this.id_txt.getText()+"'";
            //qry2="update proj_1.patient set emp_id=null where emp_id='"+this.id_txt.getText()+"'";
            //qry5="update proj_1.nurse_tech set nurse_id=null where nurse_id='"+this.id_txt.getText()+"'";
            qry3="delete from proj_1.nurse where emp_id='"+this.id_txt.getText()+"'";
            qry4="delete from proj_1.employee where emp_id='"+this.id_txt.getText()+"'";
            }
            if(this.hidden2.getText().equals("Lab Technician")){
            //qry="update proj_1.doctor set tech_id=null where tech_id='"+this.id_txt.getText()+"'";
            //qry2="update proj_1.nurse set tech_id=null where tech_id='"+this.id_txt.getText()+"'";
            //qry5="update proj_1.nurse_tech set tech_id=null where tech_id='"+this.id_txt.getText()+"'";
            qry3="delete from proj_1.lab_technician where emp_id='"+this.id_txt.getText()+"'";
            qry4="delete from proj_1.employee where emp_id='"+this.id_txt.getText()+"'";
            }
            Statement stmt=con.createStatement();
            //stmt.executeUpdate(qry);
            //stmt.executeUpdate(qry2);
            //stmt.executeUpdate(qry5);
            stmt.executeUpdate(qry3);
            stmt.executeUpdate(qry4);
            con.commit();
            con.close();
            JOptionPane.showMessageDialog(null, "Done");
        } catch (Exception ex) {
            //Logger.getLogger(ayo.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(null,ex.toString());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void pass_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ArrayList<String> temp7 = new ArrayList<>();
                edit_emp temp2 = new edit_emp(temp7);
                temp2.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Specialty;
    private javax.swing.JTextField Specialty_txt;
    private javax.swing.JTextField address_txt;
    private javax.swing.JComboBox<String> city_box;
    private javax.swing.JTextField day_txt;
    private javax.swing.JLabel dep;
    private javax.swing.JComboBox<String> dep_box;
    private javax.swing.JTextField fname_txt;
    private javax.swing.JLabel hidden;
    private javax.swing.JLabel hidden2;
    private javax.swing.JTextField id_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lname_txt;
    private javax.swing.JTextField mname_txt;
    private javax.swing.JTextField month_txt;
    private javax.swing.JTextField pass_txt;
    private javax.swing.JTextField phone_txt;
    private javax.swing.JTextField salary_txt;
    private javax.swing.JComboBox<String> sex_box;
    private javax.swing.JComboBox<String> shift_box;
    private javax.swing.JComboBox<String> type_box;
    private javax.swing.JTextField year_txt;
    // End of variables declaration//GEN-END:variables
}
