/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author momo
 */
public class edit_dep extends javax.swing.JFrame {

    /**
     * Creates new form edit_dep
     * @param data
     */
    public static JFrame temp_edit_dep;
    public edit_dep(ArrayList<String> data, JFrame parent) {
        initComponents();
                this.setResizable(false); 
        this.setLocationRelativeTo(null);
        this.dep_name_txt.setText(data.get(0));
        this.hidden.setText(data.get(0));
        this.floor.setSelectedItem(data.get(1));
        this.beds_txt.setText(data.get(2));
        temp_edit_dep=parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dep_name_txt = new javax.swing.JTextField();
        floor = new javax.swing.JComboBox<>();
        beds_txt = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        hidden = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(780, 575));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(217, 244, 255));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jLabel10.setBackground(new java.awt.Color(255, 204, 102));
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Name");
        jLabel10.setOpaque(true);
        jPanel1.add(jLabel10);
        jLabel10.setBounds(230, 130, 120, 30);

        jLabel11.setBackground(new java.awt.Color(255, 204, 102));
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Floor");
        jLabel11.setOpaque(true);
        jPanel1.add(jLabel11);
        jLabel11.setBounds(230, 210, 120, 30);

        jLabel12.setBackground(new java.awt.Color(255, 204, 102));
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Number Of Beds");
        jLabel12.setOpaque(true);
        jPanel1.add(jLabel12);
        jLabel12.setBounds(230, 280, 120, 30);

        dep_name_txt.setBackground(new java.awt.Color(204, 204, 204));
        dep_name_txt.setForeground(new java.awt.Color(0, 0, 0));
        dep_name_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dep_name_txt.setText("Name");
        dep_name_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dep_name_txtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dep_name_txtFocusLost(evt);
            }
        });
        jPanel1.add(dep_name_txt);
        dep_name_txt.setBounds(400, 130, 180, 30);

        floor.setBackground(new java.awt.Color(204, 204, 204));
        floor.setForeground(new java.awt.Color(0, 0, 0));
        floor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "G", "1st", "2nd", "3rd" }));
        jPanel1.add(floor);
        floor.setBounds(400, 210, 50, 30);

        beds_txt.setEditable(false);
        beds_txt.setBackground(new java.awt.Color(204, 204, 204));
        beds_txt.setForeground(new java.awt.Color(0, 0, 0));
        beds_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        beds_txt.setText("6");
        beds_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beds_txtActionPerformed(evt);
            }
        });
        jPanel1.add(beds_txt);
        beds_txt.setBounds(400, 280, 80, 30);

        jButton3.setBackground(new java.awt.Color(153, 204, 255));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Confirm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(90, 460, 170, 40);

        jButton4.setBackground(new java.awt.Color(255, 204, 153));
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Go Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(550, 460, 170, 40);

        jButton5.setBackground(new java.awt.Color(255, 102, 102));
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(320, 460, 170, 40);

        hidden.setText("jLabel1");
        jPanel1.add(hidden);
        hidden.setBounds(290, 220, 37, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dep_name_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dep_name_txtFocusGained
        // TODO add your handling code here:
        if (dep_name_txt.getText().equals("Name")) {
            dep_name_txt.setText("");}
    }//GEN-LAST:event_dep_name_txtFocusGained

    private void dep_name_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dep_name_txtFocusLost
        // TODO add your handling code here:
        if (dep_name_txt.getText().isEmpty()) {
            dep_name_txt.setText("Name");
        }
    }//GEN-LAST:event_dep_name_txtFocusLost

    private void beds_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beds_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beds_txtActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            DriverManager.registerDriver(new org.postgresql.Driver());
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo,"hmd","0000");
            con.setAutoCommit(false);
            String qry=null;
            String qry2=null;
            String qry3=null;
            String qry4=null;
            String qry5=null;
            String qry6=null;
            int flag=0;
            if(this.hidden.getText().equals(this.dep_name_txt.getText())){
            qry="update proj_1.department set floor='"+this.floor.getSelectedItem()+"',no_of_beds="+this.beds_txt.getText()+" where dep_name='"+this.dep_name_txt.getText()+"'";
            }
            else{
            qry="insert into proj_1.department values ('"+this.dep_name_txt.getText()+"','"+this.floor.getSelectedItem()+"',"+this.beds_txt.getText()+")";
            qry2="update proj_1.doctor set dep_name='"+this.dep_name_txt.getText()+"' where dep_name='"+this.hidden.getText()+"'";
            qry3="update proj_1.nurse set dep_name='"+this.dep_name_txt.getText()+"' where dep_name='"+this.hidden.getText()+"'";
            qry4="update proj_1.lab_technician set dep_name='"+this.dep_name_txt.getText()+"' where dep_name='"+this.hidden.getText()+"'";
            qry5="update proj_1.patient set dep_name='"+this.dep_name_txt.getText()+"' where dep_name='"+this.hidden.getText()+"'";
            qry6="delete from proj_1.department where dep_name='"+this.hidden.getText()+"'";
                flag=1;}
            Statement stmt=con.createStatement();
            stmt.executeUpdate(qry);
            if(flag==1){
            stmt.executeUpdate(qry2);
            stmt.executeUpdate(qry3);
            stmt.executeUpdate(qry4);
            stmt.executeUpdate(qry5);
            stmt.executeUpdate(qry6);
            }
            con.commit();
            con.close();
            JOptionPane.showMessageDialog(null, "Done");
            //temp_edit_dep.setVisible(true);
             new search(this).setVisible(true);
             search.setSelectedTab(1);
            this.dispose();
        } catch (Exception ex) {
            //Logger.getLogger(ayo.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(null,ex.toString());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //temp_edit_dep.setVisible(true);
        new search(this).setVisible(true);
        search.setSelectedTab(1);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            DriverManager.registerDriver(new org.postgresql.Driver());
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo,"hmd","0000");
            con.setAutoCommit(false);
            String qry=null;
            String qry2=null;
            String qry3=null;
            String qry4=null;
            String qry5=null;
            qry="update proj_1.doctor set dep_name=null where dep_name='"+this.dep_name_txt.getText()+"'";
            qry2="update proj_1.nurse set dep_name=null where dep_name='"+this.dep_name_txt.getText()+"'";
            qry3="update proj_1.lab_technician set dep_name=null where dep_name='"+this.dep_name_txt.getText()+"'";   
            qry4="update proj_1.patient set dep_name=null where dep_name='"+this.dep_name_txt.getText()+"'";
            qry5="delete from proj_1.department where dep_name='"+this.dep_name_txt.getText()+"'";
            Statement stmt=con.createStatement();
            stmt.executeUpdate(qry);
            stmt.executeUpdate(qry2);
            stmt.executeUpdate(qry3);
            stmt.executeUpdate(qry4);
            stmt.executeUpdate(qry5);
            con.commit();
            con.close();
            JOptionPane.showMessageDialog(null, "Done");
        } catch (Exception ex) {
            //Logger.getLogger(ayo.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(null,ex.toString());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_dep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_dep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_dep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_dep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ArrayList<String> temp = new ArrayList<>();
                JFrame temp2 = new JFrame();
                new edit_dep(temp,temp2).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField beds_txt;
    private javax.swing.JTextField dep_name_txt;
    private javax.swing.JComboBox<String> floor;
    private javax.swing.JLabel hidden;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
