/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author momo
 */
public class login extends javax.swing.JFrame {
    public static boolean IsDoctor = false;
    public static boolean IsNurse = false;
    public static boolean IsLT = false;
    public static String EmpID = "";
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        this.setResizable(false); 
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        IDTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ConfirmLoginButton = new javax.swing.JButton();
        PasswordTextField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(582, 440));
        setResizable(false);
        setSize(new java.awt.Dimension(660, 525));

        jPanel1.setBackground(new java.awt.Color(217, 244, 255));
        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 204, 153));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ID");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 190, 88, 21);

        IDTextField.setBackground(new java.awt.Color(204, 204, 204));
        IDTextField.setForeground(new java.awt.Color(0, 0, 0));
        IDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(IDTextField);
        IDTextField.setBounds(280, 190, 130, 20);

        jLabel3.setBackground(new java.awt.Color(255, 204, 153));
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Password");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(170, 230, 88, 21);

        ConfirmLoginButton.setBackground(new java.awt.Color(153, 204, 255));
        ConfirmLoginButton.setForeground(new java.awt.Color(0, 0, 0));
        ConfirmLoginButton.setText("LOGIN");
        ConfirmLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmLoginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ConfirmLoginButton);
        ConfirmLoginButton.setBounds(210, 300, 150, 50);

        PasswordTextField.setBackground(new java.awt.Color(204, 204, 204));
        PasswordTextField.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(PasswordTextField);
        PasswordTextField.setBounds(280, 230, 130, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\Project3.9.7\\Project3.9.4\\Project3.7\\Project3.6.2\\Project3.0\\Project\\src\\main\\java\\com\\mycompany\\project\\BallotiEnhancedsmol.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 20, 240, 160);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private String adminPass = "admin";
    
    private void ConfirmLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmLoginButtonActionPerformed
        // TODO add your handling code here:
        if(this.IDTextField.getText().equals("admin") && this.PasswordTextField.getText().equals(adminPass)){
            //this.setAlwaysOnTop(false);           
            this.dispose();
            new welcome(this).setVisible(true);
            
            return;}
        IsDoctor = Check.FoundEmp("doctor", IDTextField.getText(), PasswordTextField.getText());
        IsNurse = Check.FoundEmp("nurse", IDTextField.getText(), PasswordTextField.getText());
        IsLT = Check.FoundEmp("lab_technician", IDTextField.getText(), PasswordTextField.getText());
        EmpID = IDTextField.getText();
        
        
        if(IsDoctor || IsNurse){
            new interface_one(Check.getFullName("employee", IDTextField.getText(),
                    PasswordTextField.getText()),IDTextField.getText(),this).setVisible(true);
            this.dispose();
        }
        else if(IsLT){
            new Tech(this);
            this.dispose();
        }
        
        else{
            JOptionPane.showMessageDialog(null,
                "Wrong ID or Password.",
                "Warning",
                JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_ConfirmLoginButtonActionPerformed

    private void IDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmLoginButton;
    private javax.swing.JTextField IDTextField;
    private javax.swing.JPasswordField PasswordTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
