/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.project;

import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author momo
 */
public class manage_patient extends javax.swing.JFrame {

    /**
     * Creates new form manage_patient
     */
    public static JFrame temp_manage_patient;
    public manage_patient(String PatientID, String DoctorID,JFrame parent) {
        initComponents();
        this.setResizable(false); 
        this.setLocationRelativeTo(null);
        temp_manage_patient=parent;
        //String name=""+data.get(1)+" "+data.get(2)+" "+data.get(3)+"";
        //this.hidden.setText(data.get(0));
        //t//his.name.setText(name);
        //String PatientName = Check.getPatientName(PatientID);
        this.PatientNameLabel.setText(Check.getPatientName(PatientID));
        
        try {
            DriverManager.registerDriver(new org.postgresql.Driver());
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo,"hmd","0000");
            String sql="select * from proj_1.diagnosis where id_no='"+PatientID+"'";
            Statement stmt=con.createStatement();
            ResultSet rs= stmt.executeQuery(sql);
            String diag1;
            while(rs.next()){
                diag1=rs.getString(4);
                this.diag.append(diag1);
            }
            String sql2="select nurse_note from proj_1.patient where id_no='"+PatientID+"'";
            rs=stmt.executeQuery(sql2);
            String note="";
            while(rs.next()){
            note=rs.getString(1);
            this.note.append(note);
            }
            //System.out.println(data.get(11));
            //this.hidden2.setText(data.get(11));
            con.close();
    } catch (Exception ex) {
            //Logger.getLogger(ayo.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(null,ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PatientNameLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        diag = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        OrderButton = new javax.swing.JButton();
        DiagnoseButton = new javax.swing.JButton();
        DischargePatientButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        RefreshButton = new javax.swing.JButton();
        hidden = new javax.swing.JLabel();
        hidden2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        note = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(217, 244, 255));
        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
        });
        jPanel1.setLayout(null);

        PatientNameLabel.setBackground(new java.awt.Color(204, 204, 204));
        PatientNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        PatientNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PatientNameLabel.setOpaque(true);
        jPanel1.add(PatientNameLabel);
        PatientNameLabel.setBounds(130, 30, 300, 20);

        jLabel9.setBackground(new java.awt.Color(255, 204, 153));
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Nurse Notes");
        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9);
        jLabel9.setBounds(600, 130, 110, 20);

        jLabel10.setBackground(new java.awt.Color(255, 204, 153));
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Patient Name");
        jLabel10.setOpaque(true);
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 30, 88, 20);

        diag.setEditable(false);
        diag.setBackground(new java.awt.Color(204, 204, 204));
        diag.setColumns(20);
        diag.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        diag.setForeground(new java.awt.Color(0, 0, 0));
        diag.setRows(5);
        jScrollPane1.setViewportView(diag);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 160, 510, 280);

        jButton5.setBackground(new java.awt.Color(255, 204, 153));
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("Go Back");
        jButton5.setPreferredSize(new java.awt.Dimension(80, 23));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(760, 480, 100, 26);

        OrderButton.setBackground(new java.awt.Color(153, 204, 255));
        OrderButton.setForeground(new java.awt.Color(0, 0, 0));
        OrderButton.setText("Order Nurse");
        OrderButton.setPreferredSize(new java.awt.Dimension(80, 23));
        OrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderButtonActionPerformed(evt);
            }
        });
        jPanel1.add(OrderButton);
        OrderButton.setBounds(600, 270, 120, 26);

        DiagnoseButton.setBackground(new java.awt.Color(153, 204, 255));
        DiagnoseButton.setForeground(new java.awt.Color(0, 0, 0));
        DiagnoseButton.setText("Diagnose");
        DiagnoseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiagnoseButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DiagnoseButton);
        DiagnoseButton.setBounds(70, 450, 100, 26);

        DischargePatientButton.setBackground(new java.awt.Color(255, 102, 102));
        DischargePatientButton.setForeground(new java.awt.Color(0, 0, 0));
        DischargePatientButton.setText("Discharge");
        DischargePatientButton.setPreferredSize(new java.awt.Dimension(80, 23));
        DischargePatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DischargePatientButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DischargePatientButton);
        DischargePatientButton.setBounds(480, 450, 100, 26);

        jLabel11.setBackground(new java.awt.Color(255, 204, 153));
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Previous Diagnosis");
        jLabel11.setOpaque(true);
        jPanel1.add(jLabel11);
        jLabel11.setBounds(70, 130, 180, 20);

        RefreshButton.setBackground(new java.awt.Color(153, 204, 255));
        RefreshButton.setForeground(new java.awt.Color(0, 0, 0));
        RefreshButton.setText("Refresh");
        RefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshButtonActionPerformed(evt);
            }
        });
        jPanel1.add(RefreshButton);
        RefreshButton.setBounds(360, 290, 100, 26);

        hidden.setText("jLabel1");
        jPanel1.add(hidden);
        hidden.setBounds(90, 130, 37, 16);

        hidden2.setText("jLabel1");
        jPanel1.add(hidden2);
        hidden2.setBounds(170, 130, 37, 16);

        jScrollPane2.setBackground(new java.awt.Color(204, 204, 204));

        note.setEditable(false);
        note.setBackground(new java.awt.Color(204, 204, 204));
        note.setColumns(20);
        note.setForeground(new java.awt.Color(0, 0, 0));
        note.setRows(5);
        jScrollPane2.setViewportView(note);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(600, 160, 240, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DiagnoseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiagnoseButtonActionPerformed
        // TODO add your handling code here:
        if(login.IsDoctor){
//        String id= PatientID;
//        String id2=login.EmpID;
        Diagnose temp =new Diagnose(this);
        temp.setVisible(true);
        this.dispose();}
        else{
            JOptionPane.showMessageDialog(null, "Permission Denied, only doctors diagnose", "Permission denied", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_DiagnoseButtonActionPerformed

    private void RefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButtonActionPerformed
        // TODO add your handling code here:
//        try {
//            DriverManager.registerDriver(new org.postgresql.Driver());
//            String connInfo="jdbc:postgresql://localhost:5432/postgres";
//            Connection con=DriverManager.getConnection(connInfo,"hmd","0000");
//            String sql="select * from proj_1.diagnosis where id_no='"+interface_one.PatientID+"'";
//            Statement stmt=con.createStatement();
//            ResultSet rs= stmt.executeQuery(sql);
//            String diag1;
//            this.diag.setText("");
//            while(rs.next()){
//                diag1=rs.getString(4);
//                this.diag.append(diag1);
//            }
//            con.close();
//    } catch (Exception ex) {
//            //Logger.getLogger(ayo.class.getName()).log(Level.SEVERE, null, ex);
//            JOptionPane.showConfirmDialog(null,ex.toString());
//        }
    }//GEN-LAST:event_RefreshButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        temp_manage_patient.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed
    
    
    private void DischargePatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DischargePatientButtonActionPerformed
        // TODO add your handling code here:
        if(login.IsNurse) {
            JOptionPane.showMessageDialog(null, "Permission Denied, only doctors discharge", "Permission denied", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        String userInput = JOptionPane.showInputDialog("Enter Discharge note/Finale Diagnosis");
        if(userInput != null){
             
        try {
            
            // TODO add your handling code here:
            Connection c = Connector.getConnection();
            InputStream input;
            //sql statement
            String qry = "UPDATE proj_1.patient SET discharge_note = ? WHERE id_no = ?";
            try (PreparedStatement pstmt = c.prepareStatement(qry)) {
                pstmt.setString(1, userInput);  // Set discharge_note parameter
                pstmt.setString(2, interface_one.PatientID);  // Set id_no parameter
                
                int rowsAffected = pstmt.executeUpdate();
                

                JasperDesign jd;
                JasperReport jr;
                JasperPrint jp;
                OutputStream output;
                //jasper file in constructor
                input = new FileInputStream(new File("Patient_Discharge.jrxml"));
                jd=JRXmlLoader.load(input);
                jr=JasperCompileManager.compileReport(jd);
                //hashmap with .put method with 2 arguments: the parameter name as in your jasper report
                //and the value of the parameter that you want you reportin
                Map<String, Object> parameters = new HashMap<>();
                parameters.put("patient_id", interface_one.PatientID);
                jp=JasperFillManager.fillReport(jr, parameters, c);
                //that's it the rest is as usual
                JFrame f = new JFrame("Patient Discharge");
                f .getContentPane().add(new JRViewer(jp));
                f.pack();
                f.setSize(1920  , 1080);
                f.setVisible(true);
                
            Statement stmt=c.createStatement();
   //         ResultSet rs= stmt.executeQuery(qry);
                String sql = "delete from proj_1.patient where id_no = '" + interface_one.PatientID +"'";
                String sql2 = "delete from proj_1.diagnosis where id_no = '" + interface_one.PatientID +"'";
                stmt.executeUpdate (sql2);
                stmt.executeUpdate (sql);
                
                //            output=new FileOutputStream(new File("ayo.pdf"));
                //            JasperExportManager.exportReportToPdfStream(jp, output);
                //            output.close();
                input.close();
                c.close();
                
                note.removeAll();
                

            } catch (Exception ex) {
                Logger.getLogger(search.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(manage_patient.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        }
    }//GEN-LAST:event_DischargePatientButtonActionPerformed

    private void OrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderButtonActionPerformed
        // TODO add your handling code here:
        if(login.IsDoctor){
        new Orders(this).setVisible(true);
        this.dispose();}
        else  JOptionPane.showMessageDialog(null, "Permission Denied, only doctors Order Nurses", "Permission denied", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_OrderButtonActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formFocusGained

    private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPanel1FocusGained

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowOpened

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        try {
            DriverManager.registerDriver(new org.postgresql.Driver());
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo,"hmd","0000");
            String sql="select * from proj_1.diagnosis where id_no='"+interface_one.PatientID+"'";
            Statement stmt=con.createStatement();
            ResultSet rs= stmt.executeQuery(sql);
            String diag1;
            this.diag.setText("");
            while(rs.next()){
                diag1=rs.getString(4);
                this.diag.append(diag1);
            }
            con.close();
    } catch (Exception ex) {
            //Logger.getLogger(ayo.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(null,ex.toString());
        }
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manage_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manage_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manage_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manage_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //ArrayList<String> temp = new ArrayList<>();
                String Temp1 ="", Temp2 ="";
                JFrame temp = new JFrame();
                new manage_patient(Temp1, Temp2,temp).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DiagnoseButton;
    private javax.swing.JButton DischargePatientButton;
    private javax.swing.JButton OrderButton;
    private javax.swing.JLabel PatientNameLabel;
    private javax.swing.JButton RefreshButton;
    private javax.swing.JTextArea diag;
    private javax.swing.JLabel hidden;
    private javax.swing.JLabel hidden2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea note;
    // End of variables declaration//GEN-END:variables
}
