/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Hp
 */
public class Orders extends javax.swing.JFrame {

    /**
     * Creates new form Orders
     */
    public static JFrame temp_Orders;
    public Orders(JFrame parent) {
        initComponents();
                this.setResizable(false); 
        this.setLocationRelativeTo(null);
        temp_Orders=parent;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrderTextArea = new javax.swing.JTextArea();
        EnterOrderLabel = new javax.swing.JLabel();
        CancelOrdersButton = new javax.swing.JButton();
        ConfirmOrdersButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(217, 244, 255));
        setPreferredSize(new java.awt.Dimension(688, 360));

        jPanel1.setBackground(new java.awt.Color(217, 244, 255));
        jPanel1.setLayout(null);

        OrderTextArea.setBackground(new java.awt.Color(204, 204, 204));
        OrderTextArea.setColumns(20);
        OrderTextArea.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        OrderTextArea.setForeground(new java.awt.Color(0, 0, 0));
        OrderTextArea.setRows(5);
        jScrollPane1.setViewportView(OrderTextArea);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(90, 60, 470, 120);

        EnterOrderLabel.setBackground(new java.awt.Color(255, 204, 102));
        EnterOrderLabel.setForeground(new java.awt.Color(0, 0, 0));
        EnterOrderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EnterOrderLabel.setText("Enter Order");
        EnterOrderLabel.setOpaque(true);
        jPanel1.add(EnterOrderLabel);
        EnterOrderLabel.setBounds(90, 30, 180, 20);

        CancelOrdersButton.setBackground(new java.awt.Color(255, 204, 153));
        CancelOrdersButton.setForeground(new java.awt.Color(0, 0, 0));
        CancelOrdersButton.setText("Go Back");
        CancelOrdersButton.setPreferredSize(new java.awt.Dimension(80, 23));
        CancelOrdersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelOrdersButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CancelOrdersButton);
        CancelOrdersButton.setBounds(550, 270, 100, 26);

        ConfirmOrdersButton.setBackground(new java.awt.Color(153, 204, 255));
        ConfirmOrdersButton.setForeground(new java.awt.Color(0, 0, 0));
        ConfirmOrdersButton.setText("Confirm");
        ConfirmOrdersButton.setPreferredSize(new java.awt.Dimension(80, 23));
        ConfirmOrdersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmOrdersButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ConfirmOrdersButton);
        ConfirmOrdersButton.setBounds(420, 270, 100, 26);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmOrdersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmOrdersButtonActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            DriverManager.registerDriver(new org.postgresql.Driver());
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo,"hmd","0000");
            con.setAutoCommit(false);
            String order;
            DateTimeFormatter dtf= DateTimeFormatter.ofPattern("yyyy/MM/dd");
            LocalDateTime now = LocalDateTime.now();
            //dtf.format(now);
            //String qry="select fname,mname,lname from proj_1.employee where emp_id='"+login.EmpID+"'";
            String InsertTableOrders="";
            //String name="";
            //int flag=0;
            Statement stmt=con.createStatement();
            //ResultSet rs= stmt.executeQuery(qry);
//            while(rs.next()){
//                name="Dr. "+rs.getString(1)+" "+rs.getString(3)+"";
//            }
            String NurseID = "";
            String GetEmpID="select emp_id from proj_1.patient where id_no='"+interface_one.PatientID+"'";//retrun the count of the number of rows
            //in diagnosis that have a certain emp id and patient id
            ResultSet rs=stmt.executeQuery(GetEmpID);
            while(rs.next()){
                NurseID=rs.getString("emp_id");
                //System.out.println(flag);
            }
            
            //if the count is 0 insert new diagnosis, if not, update the previously inserted diagnosis
                order =""+dtf.format(now)+"--"+this.OrderTextArea.getText()+"";
                
                    //qry2="update proj_1.diagnosis set description= description || '"+order+"\n' where id_no='"+interface_one.PatientID+"' and doc_id='"+login.EmpID+"'";
                
                    InsertTableOrders="insert into proj_1.orders(nurse_id,doc_id,order_desc,status,\"patient_ID\") values( '"+NurseID+"','"+login.EmpID+"','"+order+"\n','false', '"+interface_one.PatientID+"')";
            
            stmt.executeUpdate(InsertTableOrders);
            con.commit();
            con.close();
            JOptionPane.showMessageDialog(null, "Done");
            temp_Orders.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            //Logger.getLogger(ayo.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
            //JOptionPane.showConfirmDialog(null,ex.toString());
        }
    }//GEN-LAST:event_ConfirmOrdersButtonActionPerformed

    private void CancelOrdersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelOrdersButtonActionPerformed
        // TODO add your handling code here:
        temp_Orders.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CancelOrdersButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame temp = new JFrame();
                new Orders(temp).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelOrdersButton;
    private javax.swing.JButton ConfirmOrdersButton;
    private javax.swing.JLabel EnterOrderLabel;
    private javax.swing.JTextArea OrderTextArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
