/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author momo
 */
public class search extends javax.swing.JFrame {

    /**
     * Creates new form Search
     */
    public static JFrame temp_search;
    public search(JFrame parent) {
        initComponents();
        fillDeps();
        this.setResizable(false); 
        this.setLocationRelativeTo(null);
        temp_search=parent;
        EmpSearchField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                SearchAndFill();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                SearchAndFill();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                // Not needed for plain text fields
            }

            
        });
        
                if (EmpSearchField.getText().isEmpty()) {
            EmpSearchField.setText("Search for Employee ID/Name...");
            EmpSearchField.setForeground(java.awt.Color.GRAY);
            //fillTablePatient();
        }
                
                
                
                pfname_txt.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                SearchAndFillPatient();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                SearchAndFillPatient();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                // Not needed for plain text fields
            }

            
        });
        
                if (pfname_txt.getText().isEmpty()) {
            pfname_txt.setText("Search for Patient ID/Name...");
            pfname_txt.setForeground(java.awt.Color.GRAY);
            //fillTablePatient();
        }

        
    }
    
    private void fillTableEmployee(String sql){
        try {         
            // TODO add your handling code here:
            DriverManager.registerDriver(new org.postgresql.Driver());
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo,"hmd","0000");
            //String sql="select emp_id, fname, mname, lname  from proj_1.employee";
            Statement stmt=con.createStatement();
            ResultSet rs= stmt.executeQuery(sql);
            DefaultTableModel EmpTableModel = (DefaultTableModel) emp_table.getModel();
            //mod.removeAllElements();
            //this.PatientTable.setModel(PatientTableModel);
            EmpTableModel.setRowCount(0);
            while(rs.next()){
                String FullName = rs.getString(2) + " " + rs.getString(3) + " " + rs.getString(4);
                //String depname=rs.getString("dep_name");
                String info[]= {rs.getString(1) , FullName};
                //System.out.println(name); 
               EmpTableModel.addRow(info);
            }
            con.close();
    } catch (Exception ex) {
            //Logger.getLogger(ayo.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(null,ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        EmpSearchField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        emp_table = new javax.swing.JTable();
        ChooseEmpType = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        deps = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        beds_lbl = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        pfname_txt = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        patient_deps = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        patient_table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(780, 575));
        setSize(new java.awt.Dimension(780, 500));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(780, 540));

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(780, 540));
        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(217, 244, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(780, 540));
        jPanel2.setLayout(null);

        jLabel4.setBackground(new java.awt.Color(255, 204, 102));
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Name");
        jLabel4.setOpaque(true);
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 30, 88, 21);

        EmpSearchField.setBackground(new java.awt.Color(204, 204, 204));
        EmpSearchField.setForeground(new java.awt.Color(102, 102, 102));
        EmpSearchField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        EmpSearchField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmpSearchFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmpSearchFieldFocusLost(evt);
            }
        });
        EmpSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpSearchFieldActionPerformed(evt);
            }
        });
        jPanel2.add(EmpSearchField);
        EmpSearchField.setBounds(130, 30, 210, 22);

        jButton2.setBackground(new java.awt.Color(153, 204, 255));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(170, 460, 130, 30);

        jButton3.setBackground(new java.awt.Color(255, 204, 153));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Go Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(470, 460, 130, 30);

        emp_table.setBackground(new java.awt.Color(204, 204, 204));
        emp_table.setForeground(new java.awt.Color(0, 0, 0));
        emp_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(emp_table);

        jPanel2.add(jScrollPane4);
        jScrollPane4.setBounds(170, 120, 430, 310);

        ChooseEmpType.setBackground(new java.awt.Color(204, 204, 204));
        ChooseEmpType.setForeground(new java.awt.Color(0, 0, 0));
        ChooseEmpType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Employees", "Doctor", "Nurse", "Lab Technician" }));
        ChooseEmpType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ChooseEmpTypeItemStateChanged(evt);
            }
        });
        ChooseEmpType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseEmpTypeActionPerformed(evt);
            }
        });
        jPanel2.add(ChooseEmpType);
        ChooseEmpType.setBounds(420, 30, 150, 21);

        jTabbedPane1.addTab("Employee", jPanel2);

        jPanel3.setBackground(new java.awt.Color(217, 244, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(659, 535));
        jPanel3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel3FocusGained(evt);
            }
        });
        jPanel3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel3ComponentShown(evt);
            }
        });
        jPanel3.setLayout(null);

        deps.setBackground(new java.awt.Color(204, 204, 204));
        deps.setForeground(new java.awt.Color(0, 0, 0));
        deps.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                depsItemStateChanged(evt);
            }
        });
        jPanel3.add(deps);
        deps.setBounds(270, 150, 240, 60);

        jButton5.setBackground(new java.awt.Color(255, 204, 153));
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("Go Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);
        jButton5.setBounds(630, 460, 130, 40);

        jButton4.setBackground(new java.awt.Color(153, 204, 255));
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(160, 360, 210, 50);

        jButton11.setBackground(new java.awt.Color(153, 204, 255));
        jButton11.setForeground(new java.awt.Color(0, 0, 0));
        jButton11.setText("Department Info Overview");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11);
        jButton11.setBounds(400, 360, 210, 50);

        beds_lbl.setBackground(new java.awt.Color(255, 204, 153));
        beds_lbl.setForeground(new java.awt.Color(0, 0, 0));
        beds_lbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        beds_lbl.setOpaque(true);
        jPanel3.add(beds_lbl);
        beds_lbl.setBounds(270, 220, 110, 30);

        jTabbedPane1.addTab("Department", jPanel3);

        jPanel4.setBackground(new java.awt.Color(217, 244, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(659, 535));
        jPanel4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel4FocusGained(evt);
            }
        });
        jPanel4.setLayout(null);

        jLabel8.setBackground(new java.awt.Color(255, 204, 102));
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Name");
        jLabel8.setOpaque(true);
        jPanel4.add(jLabel8);
        jLabel8.setBounds(30, 30, 88, 21);

        pfname_txt.setBackground(new java.awt.Color(204, 204, 204));
        pfname_txt.setForeground(new java.awt.Color(102, 102, 102));
        pfname_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pfname_txt.setText("Search for Patient ID/Name...");
        pfname_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pfname_txtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pfname_txtFocusLost(evt);
            }
        });
        pfname_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfname_txtActionPerformed(evt);
            }
        });
        jPanel4.add(pfname_txt);
        pfname_txt.setBounds(130, 30, 210, 22);

        jButton7.setBackground(new java.awt.Color(153, 204, 255));
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
        jButton7.setText("Edit");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7);
        jButton7.setBounds(170, 460, 130, 30);

        patient_deps.setBackground(new java.awt.Color(204, 204, 204));
        patient_deps.setForeground(new java.awt.Color(0, 0, 0));
        patient_deps.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                patient_depsItemStateChanged(evt);
            }
        });
        jPanel4.add(patient_deps);
        patient_deps.setBounds(420, 30, 150, 21);

        jButton8.setBackground(new java.awt.Color(255, 204, 153));
        jButton8.setForeground(new java.awt.Color(0, 0, 0));
        jButton8.setText("Go Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton8);
        jButton8.setBounds(470, 460, 130, 30);

        patient_table.setBackground(new java.awt.Color(204, 204, 204));
        patient_table.setForeground(new java.awt.Color(0, 0, 0));
        patient_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Department"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(patient_table);

        jPanel4.add(jScrollPane5);
        jScrollPane5.setBounds(170, 120, 430, 310);

        jTabbedPane1.addTab("Patient", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 780, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmpSearchFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmpSearchFieldFocusGained
        // TODO add your handling code here:
        if (EmpSearchField.getText().equals("Search for Employee ID/Name...")) {
            EmpSearchField.setForeground(java.awt.Color.black);
            EmpSearchField.setText("");}
    }//GEN-LAST:event_EmpSearchFieldFocusGained

    private void EmpSearchFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmpSearchFieldFocusLost
        // TODO add your handling code here:
        if (EmpSearchField.getText().isEmpty()) {
            EmpSearchField.setForeground(java.awt.Color.gray);
            EmpSearchField.setText("Search for Employee ID/Name...");
        }
    }//GEN-LAST:event_EmpSearchFieldFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            String id=null;
            String type=null;
            String check="";
            String dep="";
            String spec="";
            String pass="";
            int row = emp_table.getSelectedRow();
            if(row == -1){
            JOptionPane.showMessageDialog(null, "Select Employee Row", "Row Selection Error", JOptionPane.INFORMATION_MESSAGE);
            return;
            }
            DefaultTableModel empTableModel = (DefaultTableModel) emp_table.getModel();
            id=(empTableModel.getValueAt(row, 0).toString());
            DriverManager.registerDriver(new org.postgresql.Driver());
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo,"hmd","0000");
            String qry1="select *  from proj_1.employee where emp_id='"+id+"'";
            Statement stmt=con.createStatement();
            ResultSet rs= stmt.executeQuery(qry1);
            ArrayList<String> info = new ArrayList<>();
            int z;
            while(rs.next()){
                String emp_name=""+rs.getString(2)+" "+rs.getString(3)+" "+rs.getString(4)+"\n";
                System.out.println(emp_name); 
                for(z=1;z<=10;z++){
                info.add(rs.getString(z));
                }
            }
            String qry2="SELECT *\n" +
                        "FROM proj_1.employee AS e\n" +
                        "INNER JOIN proj_1.doctor AS d ON e.emp_id = d.emp_id\n" +
                        "WHERE e.emp_id = '"+info.get(0)+"'";
            rs= stmt.executeQuery(qry2);
            while(rs.next()){
            check=rs.getString(1);
            dep=rs.getString("dep_name");
            spec=rs.getString("specialty");
            pass=rs.getString("pass_word");
            }
            if (!check.isEmpty()){
            type="Doctor";
                }
            String qry3="SELECT *\n" +
                        "FROM proj_1.employee AS e\n" +
                        "INNER JOIN proj_1.nurse AS n ON e.emp_id = n.emp_id\n" +
                        "WHERE e.emp_id = '"+info.get(0)+"'";
            rs= stmt.executeQuery(qry3);
            check="";
            while(rs.next()){
            check=rs.getString(1);
            dep=rs.getString("dep_name");
            pass=rs.getString("pass_word");
            }
            if (!check.isEmpty()){
            type="Nurse";
                }
            String qry4= "SELECT *\n" +
                        "FROM proj_1.employee AS e\n" +
                        "INNER JOIN proj_1.lab_technician AS l ON e.emp_id = l.emp_id\n" +
                        "WHERE e.emp_id = '"+info.get(0)+"'";
            rs= stmt.executeQuery(qry4);
            check="";
            while(rs.next()){
            check=rs.getString(1);
            dep=rs.getString("dep_name");
            pass=rs.getString("pass_word");
            }
            if (!check.isEmpty()){
            type="Lab Technician";
                }
            info.add(type);
            info.add(dep);
            info.add(spec);
            info.add(pass);
            con.close();
        edit_emp temp=new edit_emp(info);
         temp.setVisible(true);
         this.dispose();
    } catch (Exception ex) {
            //Logger.getLogger(ayo.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(null,ex.toString());
            System.out.println(ex);
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //temp_search.setVisible(true);
        new welcome(this).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
        // TODO add your handling code here:
      // fillDeps();
    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here: 
       
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jPanel3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel3FocusGained
        // TODO add your handling code here:
     //fillDeps();                      
    }//GEN-LAST:event_jPanel3FocusGained

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            ArrayList<String> info = new ArrayList<>();
            DriverManager.registerDriver(new org.postgresql.Driver());
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo,"hmd","0000");
            String sql="select * from proj_1.department where dep_name='"+this.deps.getSelectedItem()+"'";
            Statement stmt=con.createStatement();
            ResultSet rs= stmt.executeQuery(sql);
            while(rs.next()){
                info.add(rs.getString(1)); 
                info.add(rs.getString(2)); 
                info.add(rs.getString(3)); 
            }
            con.close();
        edit_dep edit= new edit_dep(info,this);
        edit.setVisible(true);
        this.dispose();
    } catch (Exception ex) {
            //Logger.getLogger(ayo.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(null,ex.toString());
        }
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        //temp_search.setVisible(true);
        new welcome(this).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jPanel3ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel3ComponentShown
        // TODO add your handling code here:
  
    }//GEN-LAST:event_jPanel3ComponentShown

    private void pfname_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfname_txtFocusGained
        // TODO add your handling code here:
         if (pfname_txt.getText().equals("Search for Patient ID/Name...")) {
            pfname_txt.setForeground(java.awt.Color.black);
            pfname_txt.setText("");}
    }//GEN-LAST:event_pfname_txtFocusGained

    private void pfname_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfname_txtFocusLost
        // TODO add your handling code here:
        if (pfname_txt.getText().isEmpty()) {
            pfname_txt.setForeground(java.awt.Color.gray);
            pfname_txt.setText("Search for Patient ID/Name...");
        }
    }//GEN-LAST:event_pfname_txtFocusLost

    private void pfname_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfname_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfname_txtActionPerformed
        private void SearchTextFieldFocusGained(java.awt.event.FocusEvent evt) {                                            
        // TODO add your handling code here:
            if (EmpSearchField.getText().equals("Search for Employee ID/Name...")) {
            EmpSearchField.setText("");
            EmpSearchField.setForeground(java.awt.Color.black);
            //fillTablePatient();
        }
    }                                           

    private void SearchTextFieldFocusLost(java.awt.event.FocusEvent evt) {                                          
        // TODO add your handling code here:
         if (EmpSearchField.getText().isEmpty()) {
            EmpSearchField.setText("Search for Employee ID/Name...");
            EmpSearchField.setForeground(java.awt.Color.GRAY);
            fillTableEmployee(generateSQL());
        }
    }                                
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try {
            String id=null;
            String type=null;
            String check="";
            String dep="";
            String spec="";
            DriverManager.registerDriver(new org.postgresql.Driver());
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo,"hmd","0000");
            int row = patient_table.getSelectedRow();
            if(row == -1){
            JOptionPane.showMessageDialog(null, "Select Patient Row", "Row Selection Error", JOptionPane.INFORMATION_MESSAGE);
            return;
            }
            DefaultTableModel empTableModel = (DefaultTableModel) patient_table.getModel();
            id=(empTableModel.getValueAt(row, 0).toString());
            String qry1="select *  from proj_1.patient where id_no='"+id+"' ";
            Statement stmt=con.createStatement();
            ResultSet rs= stmt.executeQuery(qry1);
            ArrayList<String> info = new ArrayList<>();
            int z;
            while(rs.next()){
                String pname=""+rs.getString(2)+" "+rs.getString(3)+" "+rs.getString(4)+"\n";
                System.out.println(pname); 
                for(z=1;z<=11;z++){
                info.add(rs.getString(z));
                }
            }
            con.close();
        edit_patient temp=new edit_patient(info);
         temp.setVisible(true);
         this.dispose();
    } catch (Exception ex) {
            //Logger.getLogger(ayo.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(null,ex.toString());
            System.out.println(ex);
    }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        //temp_search.setVisible(true);
        new welcome(this).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        //temp_search.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Connection c = Connector.getConnection();
            InputStream input;
            JasperDesign jd;
            JasperReport jr;
            JasperPrint jp;
            OutputStream output;
            input = new FileInputStream(new File("dep_info.jrxml"));
            jd=JRXmlLoader.load(input);
            jr=JasperCompileManager.compileReport(jd);
            jp=JasperFillManager.fillReport(jr, null, c);
            JFrame f = new JFrame("Department_info");
            f .getContentPane().add(new JRViewer(jp));
            f.pack();
            f.setSize(1920  , 1080);
            f.setVisible(true);
            
//            output=new FileOutputStream(new File("ayo.pdf"));
//            JasperExportManager.exportReportToPdfStream(jp, output);
//            output.close();
            input.close();
            c.close();
            
        } catch (Exception ex) {
            Logger.getLogger(search.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void EmpSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpSearchFieldActionPerformed

    
   void SearchAndFill(){
            
                String searchTerm = EmpSearchField.getText();

                if (searchTerm.trim().isEmpty() || searchTerm.trim().equals("Search for Employee ID/Name...")) {
                    // If the search term is empty, fill the table with all contents
                    fillTableEmployee(generateSQL());
                } else {
                    // Perform the search based on the entered text
                    try {
                        String query = "";
                        
                        switch ((String)ChooseEmpType.getSelectedItem()) {
            
                            case "All Employees":
                                   query = "SELECT * FROM proj_1.employee WHERE (LOWER(CONCAT_WS(' ', fname, mname, lname))"
                                + " LIKE LOWER(?) OR emp_id LIKE ?)";
                                //fillTableEmployee(sql);
                                // code to be executed if variable equals value1
                                   break;

                            case "Doctor":
                                   query = "SELECT * FROM proj_1.employee AS e JOIN"
                                           + " proj_1.doctor AS d ON e.emp_id = d.emp_id"
                                           + " WHERE (LOWER(CONCAT_WS(' ', fname, mname, lname))"
                                + " LIKE LOWER(?) OR e.emp_id LIKE ?)";
                                   //fillTableEmployee(sql);
                                  // code to be executed if variable equals value2
                                   break;

                            case "Nurse":
                                   query = "SELECT * FROM proj_1.employee AS e JOIN"
                                           + " proj_1.nurse AS d ON e.emp_id = d.emp_id"
                                           + " WHERE (LOWER(CONCAT_WS(' ', fname, mname, lname))"
                                + " LIKE LOWER(?) OR e.emp_id LIKE ?)";
                                    //fillTableEmployee(sql);
                                   break;

                            case "Lab Technician":
                                   query = "SELECT * FROM proj_1.employee AS e JOIN"
                                           + " proj_1.lab_technician AS d ON e.emp_id = d.emp_id"
                                           + " WHERE (LOWER(CONCAT_WS(' ', fname, mname, lname))"
                                + " LIKE LOWER(?) OR e.emp_id LIKE ?)";
                                    //fillTableEmployee(sql);
                                   break;

                            // add more cases as needed
                            default: query = "";
                                // code to be executed if variable doesn't match any of the cases
                        }

                        
                         //query = "SELECT * FROM proj_1.employee WHERE (LOWER(CONCAT_WS(' ', fname, mname, lname))"
                               // + " LIKE LOWER(?) OR emp_id LIKE ?)";
                        Connection c = Connector.getConnection();

                        // Create a prepared statement
                        try (PreparedStatement preparedStatement = c.prepareStatement(query)) {
                            // Set the parameter in the prepared statement
                            preparedStatement.setString(1, "%" + searchTerm.toLowerCase() + "%");
                            preparedStatement.setString(2, "%" + searchTerm + "%");
                            //preparedStatement.setString(3, (String) ChooseDepartment.getSelectedItem());
                            
                            // Execute the query and get the result set
                            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                                // Populate the jTable with the search results
                                // (Assuming jTable model is DefaultTableModel)
                                DefaultTableModel model = (DefaultTableModel) emp_table.getModel();
                                model.setRowCount(0); // Clear existing rows

                                while (resultSet.next()) {
                                    // Assuming your jTable has columns id, name, blood_type
                                    String id = resultSet.getString("emp_id");
                                    String name = resultSet.getString("fname") + " " + resultSet.getString("mname")+  " " +
                                                  resultSet.getString("lname");
                                   // String depname=resultSet.getString("dep_name");
                                    //String bloodType = resultSet.getString("blood_type");

                                    // Add a new row to the jTable
                                    model.addRow(new Object[]{id, name});
                                }
                                resultSet.close();
                                preparedStatement.close();
                                c.close();
                                
                            }
                        }
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                    }
            
        }
            
        // code to be executed if variable doesn't match any of the cases
 
        }
   
        private void fillTablePatient(String sql){
        try {         
            // TODO add your handling code here:
            DriverManager.registerDriver(new org.postgresql.Driver());
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo,"hmd","0000");
            //String sql="select emp_id, fname, mname, lname  from proj_1.employee";
            Statement stmt=con.createStatement();
            ResultSet rs= stmt.executeQuery(sql);
            DefaultTableModel EmpTableModel = (DefaultTableModel) patient_table.getModel();
            //mod.removeAllElements();
            //this.PatientTable.setModel(PatientTableModel);
            EmpTableModel.setRowCount(0);
            while(rs.next()){
                String FullName = rs.getString(2) + " " + rs.getString(3) + " " + rs.getString(4);
                String depname=rs.getString("dep_name");
                String info[]= {rs.getString(1) , FullName, depname};
                //System.out.println(name); 
               EmpTableModel.addRow(info);
            }
            con.close();
    } catch (Exception ex) {
            //Logger.getLogger(ayo.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(null,ex.toString());
        }
    }
   
   void fillDeps(){
   try {
            DriverManager.registerDriver(new org.postgresql.Driver());
            String connInfo="jdbc:postgresql://localhost:5432/postgres";
            Connection con=DriverManager.getConnection(connInfo,"hmd","0000");
            String sql="select dep_name from proj_1.department";
            Statement stmt=con.createStatement();
            ResultSet rs= stmt.executeQuery(sql);
            //this.deps.removeAllItems();
            this.patient_deps.removeAllItems();
            this.patient_deps.addItem("All Departments");
            while(rs.next()){
                String depname=rs.getString(1);
                this.deps.addItem(depname);
                this.patient_deps.addItem(depname);
            }
            con.close();
    } catch (Exception ex) {
            //Logger.getLogger(ayo.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(null,ex.toString());
        }
   }
   
    void SearchAndFillPatient(){
            
                String searchTerm = pfname_txt.getText();
                //fillDeps();
                if (searchTerm.trim().isEmpty() || searchTerm.trim().equals("Search for Patient ID/Name...")) {
                    // If the search term is empty, fill the table with all contents
                    String qry="";
                    if(this.patient_deps.getSelectedItem().equals(("All Departments"))){
                    qry="select * from proj_1.patient";}
                    else{
                        qry="select * from proj_1.patient where dep_name='"+this.patient_deps.getSelectedItem()+"'";
                    }
                    fillTablePatient(qry); // define this method
                } else {
                    // Perform the search based on the entered text
                    try {
                        String query = "";
                        if(this.patient_deps.getSelectedItem().equals(("All Departments"))){
                    query= "select * from proj_1.patient where"
                                + " (LOWER(CONCAT_WS(' ', fname, mname, lname))"
                                + " LIKE LOWER(?) OR id_no LIKE ?)";}
                    else{
                        query= "select * from proj_1.patient where dep_name='"+this.patient_deps.getSelectedItem()+"' and"
                                + " (LOWER(CONCAT_WS(' ', fname, mname, lname))"
                                + " LIKE LOWER(?) OR id_no LIKE ?)";
                    }
                        
                        Connection c = Connector.getConnection();
                        // Create a prepared statement
                        try (PreparedStatement preparedStatement = c.prepareStatement(query)) {
                            // Set the parameter in the prepared statement
                            preparedStatement.setString(1, "%" + searchTerm.toLowerCase() + "%");
                            preparedStatement.setString(2, "%" + searchTerm + "%");
                            //preparedStatement.setString(3, (String) ChooseDepartment.getSelectedItem());                           
                            // Execute the query and get the result set
                            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                                // Populate the jTable with the search results
                                // (Assuming jTable model is DefaultTableModel)
                                DefaultTableModel model = (DefaultTableModel) patient_table.getModel();
                                model.setRowCount(0); // Clear existing rows
                                while (resultSet.next()) {
                                    // Assuming your jTable has columns id, name, blood_type
                                    String id = resultSet.getString("id_no");
                                    String name = resultSet.getString("fname") + " " + resultSet.getString("mname")+  " " +
                                                  resultSet.getString("lname");
                                    String depname=resultSet.getString("dep_name");
                                    //String bloodType = resultSet.getString("blood_type");
                                    // Add a new row to the jTable
                                    model.addRow(new Object[]{id, name, depname});
                                }
                                resultSet.close();
                                preparedStatement.close();
                                c.close();                              
                            }
                        }
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                    }  
        }
            
        // code to be executed if variable doesn't match any of the cases
 
        }
    
    private void ChooseEmpTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ChooseEmpTypeItemStateChanged
        // TODO add your handling code here:
        //fillTablePatient();
        if(EmpSearchField.getText().isEmpty())
        fillTableEmployee(generateSQL());
        else{
            SearchAndFill();
        }
            
        
    }//GEN-LAST:event_ChooseEmpTypeItemStateChanged

    private String generateSQL(){
        String sql = "";
        switch ((String)ChooseEmpType.getSelectedItem()) {
            
            case "All Employees":
                 return "select emp_id, fname, mname, lname  from proj_1.employee";
                //fillTableEmployee(sql);
                // code to be executed if variable equals value1
                
            case "Doctor":
                   return "SELECT e.emp_id, e.fname, e.mname, e.lname\n" +
                         "FROM proj_1.employee AS e\n" +
                         "JOIN proj_1.doctor AS d ON e.emp_id = d.emp_id; ";
                   //fillTableEmployee(sql);
                  // code to be executed if variable equals value2
                
            case "Nurse":
                    return "SELECT e.emp_id, e.fname, e.mname, e.lname\n" +
                         "FROM proj_1.employee AS e\n" +
                         "JOIN proj_1.nurse AS n ON e.emp_id = n.emp_id; ";
                    //fillTableEmployee(sql);
                    
            case "Lab Technician":
                    return "SELECT e.emp_id, e.fname, e.mname, e.lname\n" +
                         "FROM proj_1.employee AS e\n" +
                         "JOIN proj_1.lab_technician AS l ON e.emp_id = l.emp_id; ";
                    //fillTableEmployee(sql);
                
            // add more cases as needed
            default: return "";
        }
    }
    public static void setSelectedTab(int tabIndex) {
        jTabbedPane1.setSelectedIndex(tabIndex);
    }
    
    
    private void ChooseEmpTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseEmpTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChooseEmpTypeActionPerformed

    private void patient_depsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_patient_depsItemStateChanged
        // TODO add your handling code here:
        String qry="select * from proj_1.patinet where dep_name='"+this.patient_deps.getSelectedItem()+"'";
         if(pfname_txt.getText().isEmpty())
        fillTablePatient(qry);
        else{
            SearchAndFillPatient();
        }
    }//GEN-LAST:event_patient_depsItemStateChanged

    private void jPanel4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel4FocusGained
        // TODO add your handling code here:
        //fillDeps();
      
    }//GEN-LAST:event_jPanel4FocusGained

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //fillDeps();
    }//GEN-LAST:event_formWindowOpened

    private void depsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_depsItemStateChanged
        try {
            // TODO add your handling code here:
            Connection c = Connector.getConnection();
            Statement stmt=c.createStatement();    
            Integer total =0;
            String qry="select count(*) from proj_1.patient where dep_name='"+this.deps.getSelectedItem()+"'";
            ResultSet rs= stmt.executeQuery(qry);
            while(rs.next()){
            total = rs.getInt(1);
            }
            total=6-total;
            beds_lbl.setText(total.toString()+" Beds Available");
            
        } catch (SQLException ex) {
            Logger.getLogger(search.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_depsItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame temp = new JFrame();
                new search(temp).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ChooseEmpType;
    private javax.swing.JTextField EmpSearchField;
    private javax.swing.JLabel beds_lbl;
    private javax.swing.JComboBox<String> deps;
    private javax.swing.JTable emp_table;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> patient_deps;
    private javax.swing.JTable patient_table;
    private javax.swing.JTextField pfname_txt;
    // End of variables declaration//GEN-END:variables
}
